const SUBJECTS=[{id:'etica',name:'Ética',topics:['Publicidade','Honorários']},{id:'civil',name:'Civil',topics:['Contratos','Prescrição']},{id:'tributario',name:'Tributário',topics:['Crédito','Lançamento']},{id:'trabalho',name:'Trabalho',topics:['Vínculo','Jornada']}];
const QUESTIONS=SUBJECTS.flatMap(s=>s.topics.map((t,i)=>({id:s.id+i,subject:s.id,topic:t,text:'Em '+s.name+', qual rotina de estudo é mais adequada para revisar '+t+'?',options:['Só ler resumo','Resolver questões e registrar erro','Pular revisão','Trocar de tema'],correct:1,explanation:'Questão, conferência e registro de erro criam revisão útil.'})));
const $=id=>document.getElementById(id),KEY='oabv7';let state=JSON.parse(localStorage.getItem(KEY)||'{"attempts":[],"wrongs":[],"sessions":[],"studied":[],"profile":{"name":"Usuário local"}}'),session=null,sel='etica';
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function show(page){document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.dataset.view===page));document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.page===page));$('pageTitle').textContent={painel:'Painel',estudo:'Estudo',questoes:'Questões',erros:'Caderno de erros',provas:'Provas oficiais',perfil:'Perfil'}[page]||'Painel'}
function stats(){let n=state.attempts.length,c=state.attempts.filter(a=>a.ok).length;return{n,c,p:n?Math.round(c/n*100):0}}
function dash(){let s=stats();$('accuracy').textContent=s.p+'%';$('answeredCount').textContent=s.n+' questões respondidas';$('dueCount').textContent=state.wrongs.filter(w=>!w.done).length;$('weakSubject').textContent='--';$('progressGeneral').textContent=Math.round(state.studied.length/SUBJECTS.length*100)+'%';$('progressBar').style.width=Math.round(state.studied.length/SUBJECTS.length*100)+'%';$('lastSession').textContent=state.sessions.at(-1)?'Último resultado: '+state.sessions.at(-1).score+'/'+state.sessions.at(-1).total:'Nenhum bloco finalizado.';$('nextActions').innerHTML='<div class="action-item"><div><strong>Estudar agora</strong><small>Iniciar bloco de questões.</small></div><button class="btn secondary" id="goTrain">Abrir</button></div>';$('goTrain').onclick=()=>start('treino')}
function study(){$('subjectList').innerHTML=SUBJECTS.map(s=>'<button class="subject-btn '+(s.id===sel?'active':'')+'" data-s="'+s.id+'"><strong>'+s.name+'</strong><small>'+s.topics.join(', ')+'</small></button>').join('');document.querySelectorAll('[data-s]').forEach(b=>b.onclick=()=>{sel=b.dataset.s;study()});let s=SUBJECTS.find(x=>x.id===sel);$('subjectName').textContent=s.name;$('subjectPriority').textContent='Prioridade';$('subjectTarget').textContent='10 questões';$('subjectStatus').textContent=state.studied.includes(sel)?'Estudada':'Pendente';$('subjectAccuracy').textContent='--';$('subjectTopics').innerHTML=s.topics.map(t=>'<span class="chip">'+t+'</span>').join('')}
function start(mode=$('modeSelect').value){let qs=(mode==='revisao'?state.wrongs.filter(w=>!w.done).map(w=>QUESTIONS.find(q=>q.id===w.qid)).filter(Boolean):QUESTIONS.filter(q=>$('subjectSelect').value==='todas'||q.subject===$('subjectSelect').value)).slice(0,Number($('questionLimit').value||5));if(!qs.length){$('appAlert').hidden=false;$('appAlert').textContent='Não há questões neste filtro.';return}session={mode,qs,i:0,ans:{}};$('sessionEmpty').hidden=true;$('resultArea').hidden=true;$('sessionArea').hidden=false;show('questoes');renderQ()}
function renderQ(){let q=session.qs[session.i],a=session.ans[q.id];$('sessionMode').textContent=session.mode;$('sessionTitle').textContent='Questão '+(session.i+1)+' de '+session.qs.length;$('sessionScore').textContent=Object.keys(session.ans).length+'/'+session.qs.length;$('questionSubject').textContent=SUBJECTS.find(s=>s.id===q.subject).name;$('questionTopic').textContent=q.topic;$('questionText').textContent=q.text;$('questionNav').innerHTML=session.qs.map((x,i)=>'<button class="q-dot '+(i===session.i?'active':'')+'" data-go="'+i+'">'+(i+1)+'</button>').join('');document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>{session.i=+b.dataset.go;renderQ()});$('answerList').innerHTML=q.options.map((o,i)=>'<button class="answer '+(a&&i===q.correct&&session.mode!=='prova'?'ok':'')+'" data-a="'+i+'">'+String.fromCharCode(65+i)+') '+o+'</button>').join('');document.querySelectorAll('[data-a]').forEach(b=>b.onclick=()=>pick(+b.dataset.a));$('previousQuestion').disabled=session.i===0;$('nextQuestion').disabled=session.i===session.qs.length-1;$('finishSession').disabled=!Object.keys(session.ans).length;$('feedback').hidden=!(a&&session.mode!=='prova');if(a&&session.mode!=='prova')$('feedback').textContent=(a.ok?'Correto. ':'Errado. ')+q.explanation}
function pick(i){let q=session.qs[session.i],ok=i===q.correct;session.ans[q.id]={i,ok};if(session.mode!=='prova'){state.attempts.push({qid:q.id,ok,subject:q.subject});if(ok&&session.mode==='revisao')state.wrongs.filter(w=>w.qid===q.id).forEach(w=>w.done=true);if(!ok)state.wrongs.push({qid:q.id,subject:q.subject,topic:q.topic,done:false});save()}renderQ()}
function finish(){if(session.mode==='prova')session.qs.forEach(q=>{let a=session.ans[q.id];if(a){state.attempts.push({qid:q.id,ok:a.ok,subject:q.subject});if(!a.ok)state.wrongs.push({qid:q.id,subject:q.subject,topic:q.topic,done:false})}});let total=Object.keys(session.ans).length,score=Object.values(session.ans).filter(a=>a.ok).length;state.sessions.push({score,total});save();$('sessionArea').hidden=true;$('resultArea').hidden=false;$('resultArea').innerHTML='<div class="result-grid"><div class="result-cell"><small>Resultado</small><strong>'+score+'/'+total+'</strong></div></div>';dash();errors()}
function errors(){$('errorList').innerHTML=state.wrongs.filter(w=>!w.done).length?state.wrongs.filter(w=>!w.done).map((w,i)=>'<article class="error-card"><strong>'+w.topic+'</strong><p>'+((QUESTIONS.find(q=>q.id===w.qid)||{}).text||'')+'</p><button class="btn secondary" data-fix="'+i+'">Dominar</button></article>').join(''):'<div class="empty-state">Nenhum erro neste filtro.</div>';document.querySelectorAll('[data-fix]').forEach(b=>b.onclick=()=>{state.wrongs[+b.dataset.fix].done=true;save();errors();dash()})}
function bind(){document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>show(b.dataset.page));$('quickTrain').onclick=()=>start('treino');$('quickReview').onclick=()=>start('revisao');$('startSession').onclick=()=>start();$('trainSubject').onclick=()=>{show('questoes');$('subjectSelect').value=sel;start('treino')};$('toggleStudied').onclick=()=>{state.studied=state.studied.includes(sel)?state.studied.filter(x=>x!==sel):state.studied.concat(sel);save();study();dash()};$('previousQuestion').onclick=()=>{if(session.i>0){session.i--;renderQ()}};$('nextQuestion').onclick=()=>{if(session.i<session.qs.length-1){session.i++;renderQ()}};$('finishSession').onclick=finish;$('saveProfile').onclick=()=>{state.profile.name=$('profileName').value||'Usuário local';save();$('sideUser').textContent=state.profile.name};$('googleLogin').onclick=()=>{$('authNotice').textContent='Login configurado; progresso ainda local.'};$('logout').onclick=()=>{$('authNotice').textContent='Sessão local.'}}
$('subjectSelect').innerHTML='<option value="todas">Todas</option>'+SUBJECTS.map(s=>'<option value="'+s.id+'">'+s.name+'</option>').join('');$('sideUser').textContent=state.profile.name;$('profileName').value=state.profile.name==='Usuário local'?'':state.profile.name;bind();study();errors();dash();
