import { getAllQuestions } from './question-bank.js';

const CFG=window.OAB_CONFIG;
const SUBJECTS=window.OAB_SUBJECTS||[];
const INTEL=window.OAB_INTELLIGENCE||null;
const BUILTIN=[...(window.OAB_QUESTIONS||[])];
const STORAGE_KEY='oab-aprova-premium-v1';
const CAL_KEY='oab-aprova-calendar-v1';
const DAY=86400000,HOUR=3600000;
const $=id=>document.getElementById(id);
const $$=s=>[...document.querySelectorAll(s)];
const now=()=>Date.now();
const clamp=(v,a,b)=>Math.min(b,Math.max(a,v));
const pct=v=>`${Math.round((v||0)*100)}%`;
let QUESTIONS=[...BUILTIN],state=loadState(),selectedSubject='etica',selectedMode='adaptive',session=null,timer=null;

const OFFICIAL_CAL={edital:'2026-09-21',open:'2026-09-28',close:'2026-10-05',exam:'2027-01-10'};
const BASES={
  etica:'Lei 8.906/1994 (EOAB), Código de Ética e Disciplina e Provimento CFOAB 205/2021 quando houver publicidade.',
  constitucional:'Constituição Federal de 1988 e legislação do controle/remédios constitucionais conforme o instituto.',
  civil:'Código Civil (Lei 10.406/2002).',
  'processo-civil':'Código de Processo Civil (Lei 13.105/2015).',
  penal:'Código Penal e legislação penal especial pertinente.',
  'processo-penal':'Código de Processo Penal, Lei de Execução Penal e legislação processual penal especial pertinente.',
  tributario:'Constituição Federal e Código Tributário Nacional.',
  administrativo:'Constituição Federal, Lei 14.133/2021, Lei 8.429/1992, LINDB e legislação administrativa pertinente.',
  empresarial:'Código Civil, Lei 6.404/1976, Lei 11.101/2005 e legislação empresarial específica.',
  trabalho:'Constituição Federal e CLT.',
  'processo-trabalho':'CLT e CPC em aplicação subsidiária/supletiva quando cabível.',
  consumidor:'Código de Defesa do Consumidor.',eca:'Estatuto da Criança e do Adolescente.',humanos:'Constituição Federal e tratados internacionais de direitos humanos pertinentes.',
  filosofia:'Teorias e autores cobrados pela FGV conforme o enunciado.',internacional:'Constituição Federal, LINDB, tratados e legislação internacional pertinente.',ambiental:'Constituição Federal, Lei 6.938/1981 e legislação ambiental pertinente.',
  eleitoral:'Constituição Federal, Código Eleitoral e legislação eleitoral pertinente.',previdenciario:'Constituição Federal e legislação previdenciária pertinente.',financeiro:'Constituição Federal, Lei 4.320/1964 e Lei de Responsabilidade Fiscal.'
};
const TOPIC_BASES={
  publicidade:'EOAB, Código de Ética e Provimento CFOAB 205/2021.',honorarios:'EOAB e Código de Ética e Disciplina.',prerrogativas:'EOAB, especialmente o regime de direitos e prerrogativas da advocacia.',
  controle_constitucionalidade:'CF/88, Lei 9.868/1999 e Lei 9.882/1999 conforme a ação.',remedios_constitucionais:'CF/88 e legislação específica do remédio constitucional.',
  tutela_provisoria:'CPC, regime das tutelas provisórias.',cumprimento_execucao:'CPC, cumprimento de sentença e execução.',recursos:'Legislação processual da matéria e regras específicas do recurso cobrado.',
  credito_tributario:'CTN, constituição, suspensão, extinção e exclusão do crédito tributário.',competencia_limitacoes:'CF/88 e CTN, competência e limitações ao poder de tributar.',
  licitacoes_contratos:'Lei 14.133/2021.',improbidade:'Lei 8.429/1992 com as alterações vigentes.',atos_administrativos:'Regime jurídico dos atos administrativos e LINDB quando pertinente.',
  teoria_crime:'Código Penal, teoria do delito.',prisoes_cautelares:'CPP, prisões e medidas cautelares.',investigacao_acao:'CPP, investigação e ação penal.',
  relacao_contrato:'CLT, relação de emprego e contrato de trabalho.',jornada_descanso:'CLT, jornada, intervalos, repousos e férias.',
  recuperacao_falencia:'Lei 11.101/2005.'
};

function defaultState(){return {version:4,profile:{targetDate:OFFICIAL_CAL.exam,targetScore:45,dailyMinutes:60,strategy:'core'},attempts:[],reviews:{},sessions:[],settings:{subjectFilter:'core'},updatedAt:now()};}
function loadState(){try{const raw=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null');const b=defaultState();return raw?{...b,...raw,profile:{...b.profile,...(raw.profile||{})},settings:{...b.settings,...(raw.settings||{})}}:b;}catch{return defaultState();}}
function persist(){state.updatedAt=now();localStorage.setItem(STORAGE_KEY,JSON.stringify(state));}
function subj(id){return SUBJECTS.find(s=>s.id===id)||{id,name:id,q:1,core:false};}
function qById(id){return QUESTIONS.find(q=>q.id===id);}
function canon(id){try{return INTEL?.canonicalSubject(id)||id;}catch{return id;}}
function topicOf(q){if(!q)return null;const raw=`${q.topic||''} ${q.text||''} ${(q.options||[]).join(' ')}`;try{return INTEL?.resolveTopic(q.subject,raw)||INTEL?.resolveTopic(q.subject,q.topic)||null;}catch{return null;}}
function topicLabel(q){return topicOf(q)?.label||String(q?.topic||'Conteúdo geral').replace(/\s*•\s*prova oficial/ig,'');}
function topicId(q){return topicOf(q)?.id||'geral';}
function legalBasis(q){const rows=(q?.legalBasis||[]).map(x=>typeof x==='string'?x:(x?.label||x?.title||'')).filter(Boolean);return rows.length?rows.slice(0,3).join(' • '):null;}
function sourceBase(q){return legalBasis(q)||TOPIC_BASES[topicId(q)]||BASES[canon(q.subject)]||'Legislação específica do instituto cobrado.';}
function usefulExplanation(q){const e=String(q?.explanation||'').trim();if(!e||/Questão oficial preservada sem comentário editorial automático/i.test(e)||/Gabarito definitivo oficial/i.test(e))return null;return e;}
function attemptsForQ(id){return state.attempts.filter(a=>a.qid===id);}
function conceptKeyQ(q){const sid=canon(q?.subject),t=topicOf(q),raw=INTEL?.normalize?.(q?.topic||q?.ruleId||q?.id||'geral')||String(q?.topic||q?.ruleId||q?.id||'geral');return `${sid}|${t?.id||`raw:${raw}`}`;}
function conceptKeyA(a){const sid=canon(a?.subject);let t=null;try{t=INTEL?.resolveTopic(sid,a?.topic)||null;}catch{}const raw=INTEL?.normalize?.(a?.topic||a?.ruleId||a?.qid||'geral')||String(a?.topic||a?.ruleId||a?.qid||'geral');return `${sid}|${t?.id||`raw:${raw}`}`;}
function attemptsForConcept(q){const key=conceptKeyQ(q);return state.attempts.filter(a=>conceptKeyA(a)===key);}
function recurrence(q){const qa=attemptsForQ(q.id),ca=attemptsForConcept(q);return {qWrong:qa.filter(a=>!a.correct).length,cWrong:ca.filter(a=>!a.correct).length,qTotal:qa.length,cTotal:ca.length};}
function recurrentConceptCount(){const keys=new Set();for(const r of Object.values(state.reviews||{})){if(r.mastered)continue;const q=qById(r.qid);if(q&&attemptsForConcept(q).filter(a=>!a.correct).length>=2)keys.add(conceptKeyQ(q));}return keys.size;}
function dueLabel(ts){const d=Number(ts||0)-now();if(d<=0)return'vencida';if(d<DAY)return`em ${Math.max(1,Math.ceil(d/HOUR))}h`;const n=Math.ceil(d/DAY);return n===1?'amanhã':`em ${n} dias`;}

function readCal(){try{return {...OFFICIAL_CAL,...JSON.parse(localStorage.getItem(CAL_KEY)||'{}')};}catch{return {...OFFICIAL_CAL};}}
function dateLocal(s){return new Date(`${s}T12:00:00`);}
function daysUntil(s){return Math.ceil((dateLocal(s)-new Date())/DAY);}
function fmtDate(s){return dateLocal(s).toLocaleDateString('pt-BR');}
function countdownText(s){const d=daysUntil(s);return d>1?`${d} dias`:d===1?'amanhã':d===0?'hoje':`${Math.abs(d)}d atrás`;}
function renderCalendar(){const c=readCal();$('editalCountdown').textContent=countdownText(c.edital);$('editalDateLabel').textContent=fmtDate(c.edital);$('inscriptionOpenCountdown').textContent=countdownText(c.open);$('inscriptionOpenLabel').textContent=fmtDate(c.open);$('inscriptionCloseCountdown').textContent=countdownText(c.close);$('inscriptionCloseLabel').textContent=fmtDate(c.close);$('examCountdown').textContent=countdownText(c.exam);$('examDateLabel').textContent=fmtDate(c.exam);$('daysToExam').textContent=Math.max(0,daysUntil(state.profile.targetDate||c.exam));$('calEdital').value=c.edital;$('calOpen').value=c.open;$('calClose').value=c.close;$('calExam').value=c.exam;const t=now(),o=dateLocal(c.open).getTime(),cl=dateLocal(c.close).getTime();$('calendarStatus').textContent=t<o?'inscrições ainda não abertas':t<=cl?'inscrições abertas':'inscrições encerradas';}

function stats(id){if(INTEL)return INTEL.subjectStats(state,id);const a=state.attempts.filter(x=>x.subject===id),correct=a.filter(x=>x.correct).length,n=a.length;return {n,correct,wrong:n-correct,raw:n?correct/n:0,estimated:n?correct/n:.4,open:Object.values(state.reviews).filter(r=>r.subject===id&&!r.mastered).length,due:Object.values(state.reviews).filter(r=>r.subject===id&&!r.mastered&&r.due<=now()).length,potential:0};}
function overall(){const total=state.attempts.length,correct=state.attempts.filter(a=>a.correct).length,projected=SUBJECTS.reduce((n,s)=>n+s.q*stats(s.id).estimated,0),due=Object.values(state.reviews).filter(r=>!r.mastered&&r.due<=now()).length,recurrent=recurrentConceptCount(),unclassified=state.attempts.filter(a=>!a.correct&&!a.cause).length;return {total,correct,accuracy:total?correct/total:0,projected,due,recurrent,unclassified};}
function ranking(){return INTEL?INTEL.rankSubjects(state,{strategy:state.profile.strategy}):SUBJECTS.map(s=>({id:s.id,name:s.name,q:s.q,stats:stats(s.id),focus:s.q*(1-stats(s.id).estimated),potential:0})).sort((a,b)=>b.focus-a.focus);}
function recs(n=4){return INTEL?INTEL.recommendations(state,{strategy:state.profile.strategy,limit:n}):[];}

function page(name){$$('.page').forEach(x=>x.classList.toggle('active',x.dataset.view===name));$$('[data-page]').forEach(x=>x.classList.toggle('active',x.dataset.page===name));const labels={dashboard:['CENTRAL DE APROVAÇÃO','Painel de aprovação'],plan:['ESTRATÉGIA','Plano adaptativo'],study:['CONTEÚDO','Matérias'],questions:['TREINO','Questões'],errors:['MEMÓRIA','Erros e reforço'],analytics:['MÉTRICAS','Desempenho']};$('pageEyebrow').textContent=labels[name]?.[0]||'OAB APROVA';$('pageTitle').textContent=labels[name]?.[1]||'OAB APROVA';if(name==='errors')renderErrors();if(name==='analytics')renderAnalytics();window.scrollTo({top:0,behavior:'smooth'});}
function notice(msg){$('notice').textContent=msg;$('notice').classList.remove('hidden');setTimeout(()=>$('notice').classList.add('hidden'),4500);}

function renderDashboard(){renderCalendar();const o=overall();$('projectedScore').textContent=o.projected.toFixed(1);$('scoreRing').style.setProperty('--pct',`${clamp(o.projected/80,0,1)*360}deg`);$('projectionConfidence').textContent=o.total<20?'projeção inicial — aumente a amostra':`${o.total} respostas usadas na projeção`;$('safeTarget').textContent=state.profile.targetScore;$('dashboardDue').textContent=o.due;$('metricAttempts').textContent=o.total;$('metricSessions').textContent=`${state.sessions.length} sessões`;$('metricAccuracy').textContent=pct(o.accuracy);$('metricRecurrent').textContent=o.recurrent;$('metricUnclassified').textContent=o.unclassified;let label='Sem diagnóstico',text='Resolva questões para formar amostra.',kind='neutral';if(o.total>=20&&o.projected>=45){label='Zona de segurança';text='A projeção está acima da meta; preserve os pontos com revisão.';kind='good';}else if(o.total>=20&&o.projected>=40){label='Zona de aprovação';text='A projeção cruza 40, mas ainda falta margem.';kind='warn';}else if(o.total>=20){label='Risco de reprovação';text='A prioridade é recuperar conceitos de maior peso.';kind='bad';}$('riskLabel').textContent=label;$('riskText').textContent=text;$('riskDot').className=`status-dot ${kind}`;const rs=recs(4);$('priorityList').innerHTML=rs.length?rs.map((r,i)=>`<div class="priority-row"><div class="priority-rank">${i+1}</div><div><strong>${r.subjectName}</strong><small>${r.topic.label} • domínio ${pct(r.stats.estimated)} • ${r.action.label}</small></div><div class="priority-value"><b>+${r.recoverable.toFixed(1)}</b><span>pts recuperáveis</span></div></div>`).join(''):'<div class="muted">Faça algumas questões para formar a fila adaptativa.</div>';const top=rs[0],mins=state.profile.dailyMinutes||60;$('routineBox').innerHTML=`<div class="routine-step"><b>1</b><div><strong>${Math.max(10,Math.round(mins*.25))} min • erros vencidos/reincidentes</strong><span>Feche primeiro falhas já descobertas.</span></div></div><div class="routine-step"><b>2</b><div><strong>${Math.max(15,Math.round(mins*.45))} min • ${top?`${top.subjectName}: ${top.topic.label}`:'bloco adaptativo'}</strong><span>Questões antes da teoria.</span></div></div><div class="routine-step"><b>3</b><div><strong>${Math.max(10,Math.round(mins*.30))} min • reforço</strong><span>Regra mínima + nova aplicação do mesmo conceito.</span></div></div>`;}

function renderPlan(){const rows=ranking();$('planRanking').innerHTML=rows.map((r,i)=>`<div class="ranking-item"><div class="ranking-score">${i+1}</div><div><strong>${r.name}</strong><small>${r.topTopic?`${r.topTopic.topic.label} • `:''}${r.q} questões • domínio ${pct(r.stats.estimated)} • ${r.stats.wrong||0} erros</small></div><div class="priority-pill">${Math.round(r.focus||0)}</div></div>`).join('');$('targetDate').value=state.profile.targetDate||readCal().exam;$('targetScore').value=state.profile.targetScore||45;$('dailyMinutes').value=state.profile.dailyMinutes||60;$('strategy').value=state.profile.strategy||'core';}
function renderStudy(){const filter=state.settings.subjectFilter||'core',arr=filter==='core'?SUBJECTS.filter(s=>s.core):SUBJECTS;$('subjectList').innerHTML=arr.map(s=>{const st=stats(s.id);return `<button class="subject-btn ${selectedSubject===s.id?'active':''}" data-subject="${s.id}"><div class="line1"><strong>${s.name}</strong><b>${s.q}Q</b></div><span>${st.n?`${pct(st.estimated)} domínio • ${st.wrong} erros`:'sem diagnóstico'}</span></button>`}).join('');$$('[data-subject]').forEach(b=>b.onclick=()=>{selectedSubject=b.dataset.subject;renderStudy();});const s=subj(selectedSubject),st=stats(s.id),top=INTEL?.rankTopics(state,{subject:s.id})?.[0];$('subjectTier').textContent=s.core?'NÚCLEO 62':'COMPLEMENTAR';$('subjectName').textContent=s.name;$('subjectWeight').textContent=`${s.q} questões`;$('subjectEstimated').textContent=pct(st.estimated);$('subjectSample').textContent=st.n;$('subjectErrors').textContent=st.open||0;$('subjectGain').textContent=`+${(st.potential||0).toFixed(1)} pts`;$('subjectAdvice').textContent=top?`Próximo alvo: ${top.topic.label}. ${top.action.label}. ${INTEL.explainRecommendation(top)}`:'Faça um diagnóstico curto antes de abrir teoria.';const topics=INTEL?INTEL.topicObjects(s.id).map(x=>x.label):s.topics||[];$('subjectTopics').innerHTML=topics.map(t=>`<span class="chip">${t}</span>`).join('');$('videoSubject').href=`materiais.html?subject=${encodeURIComponent(s.id)}`;}

function uniqueFamilies(arr){const seen=new Set();return arr.filter(q=>{const k=q.ruleId||q.sourceQuestionId||q.officialQuestionId||q.id;if(seen.has(k))return false;seen.add(k);return true;});}
function makePool(mode,limit,subject='all'){
 let base=QUESTIONS.filter(q=>subject==='all'?true:canon(q.subject)===canon(subject));
 if(state.profile.strategy==='core'&&subject==='all')base=base.filter(q=>subj(canon(q.subject)).core);
 const enriched=base.map(q=>({...q,topic:topicLabel(q)}));
 if(mode==='review'){
   const ordered=Object.values(state.reviews).filter(r=>!r.mastered).sort((a,b)=>{const ar=(a.due<=now()?0:1),br=(b.due<=now()?0:1);if(ar!==br)return ar-br;return (b.lapses||b.wrongCount||0)-(a.lapses||a.wrongCount||0)||a.due-b.due;}).map(r=>qById(r.qid)).filter(Boolean).filter(q=>subject==='all'||canon(q.subject)===canon(subject));
   return ordered.slice(0,limit);
 }
 if(mode==='adaptive'&&INTEL)return INTEL.selectAdaptiveQuestions(enriched,state,{limit,strategy:state.profile.strategy,subject});
 if(mode==='exam'){const out=[];const allowed=subject==='all'?(state.profile.strategy==='core'?SUBJECTS.filter(s=>s.core):SUBJECTS):[subj(subject)],den=allowed.reduce((n,s)=>n+s.q,0);for(const s of allowed){out.push(...uniqueFamilies(base.filter(q=>canon(q.subject)===s.id).sort(()=>Math.random()-.5)).slice(0,Math.max(1,Math.round(limit*s.q/den))));}return uniqueFamilies(out).sort(()=>Math.random()-.5).slice(0,limit);}
 return uniqueFamilies(base.sort(()=>Math.random()-.5)).slice(0,limit);
}
function renderQuestionSelectors(){const prev=$('questionSubject').value;$('questionSubject').innerHTML='<option value="all">Todas</option>'+SUBJECTS.filter(s=>QUESTIONS.some(q=>canon(q.subject)===s.id)).map(s=>`<option value="${s.id}">${s.name}</option>`).join('');if([...$('questionSubject').options].some(o=>o.value===prev))$('questionSubject').value=prev;$('errorSubject').innerHTML='<option value="all">Todas as matérias</option>'+SUBJECTS.map(s=>`<option value="${s.id}">${s.name}</option>`).join('');}
function startSession(mode=selectedMode,limit=Number($('questionLimit').value||10),subject=$('questionSubject').value||'all'){let qs=makePool(mode,limit,subject);if(!qs.length&&mode==='review'){notice('Não há revisão aberta. Iniciando bloco adaptativo.');mode='adaptive';qs=makePool(mode,limit,subject);}if(!qs.length){notice('Nenhuma questão disponível neste filtro.');return;}session={mode,qs,index:0,answers:{},startedAt:now(),questionStartedAt:now()};$('sessionSetup').classList.add('hidden');$('sessionResult').classList.add('hidden');$('sessionArea').classList.remove('hidden');page('questions');startTimer();renderQuestion();}
function startTimer(){clearInterval(timer);timer=setInterval(()=>{if(!session)return;const s=Math.floor((now()-session.startedAt)/1000);$('sessionTimer').textContent=`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;},1000);}
function reviewFor(q){return state.reviews[q.id]||null;}
function updateReview(q,correct){const old=state.reviews[q.id];if(!correct){const wrong=(old?.wrongCount||0)+1,lapses=(old?.lapses||0)+1,conceptWrong=attemptsForConcept(q).filter(a=>!a.correct).length,recurrent=wrong>=2||conceptWrong>=2;state.reviews[q.id]={...(old||{}),qid:q.id,subject:canon(q.subject),topic:topicLabel(q),due:now()+(recurrent?8*HOUR:DAY),interval:recurrent?1/3:1,streak:0,mastered:false,lastResult:false,lastSeen:now(),cause:null,wrongCount:wrong,lapses};return;}if(old){const intervals=[3,7,14,30,60],streak=(old.streak||0)+1,interval=intervals[Math.min(streak-1,intervals.length-1)];state.reviews[q.id]={...old,due:now()+interval*DAY,interval,streak,mastered:streak>=6,lastResult:true,lastSeen:now()};}}
function answerQuestion(choice){const q=session.qs[session.index];if(session.answers[q.id])return;const correct=choice===q.correct,timeMs=now()-session.questionStartedAt,topic=topicLabel(q);session.answers[q.id]={choice,correct,timeMs,cause:null};state.attempts.push({qid:q.id,ruleId:q.ruleId||null,subject:canon(q.subject),topic,correct,choice,timeMs,mode:session.mode,ts:now(),cause:null,origin:q.origin||null});updateReview(q,correct);persist();renderQuestion();renderDashboard();renderErrors();}
function classifyCause(cause){if(!session)return;const q=session.qs[session.index],ans=session.answers[q.id];if(!ans||ans.correct)return;ans.cause=cause;const last=[...state.attempts].reverse().find(a=>a.qid===q.id&&a.ts>=session.startedAt);if(last)last.cause=cause;if(state.reviews[q.id])state.reviews[q.id].cause=cause;persist();renderQuestion();renderErrors();}
function addReinforcement(){if(!session)return;const q=session.qs[session.index],sid=canon(q.subject),key=conceptKeyQ(q);let same=QUESTIONS.filter(x=>x.id!==q.id&&conceptKeyQ(x)===key&&!session.qs.some(y=>y.id===x.id));if(!same.length){notice('Não há outra questão desse conceito no banco atual. O conceito ficou registrado para revisão.');return;}if(INTEL)same=INTEL.selectAdaptiveQuestions(same.map(x=>({...x,topic:topicLabel(x)})),state,{limit:same.length,strategy:state.profile.strategy,subject:sid});session.qs.splice(session.index+1,0,same[0]);notice('Questão de reforço inserida logo a seguir.');renderQuestion();}
function feedbackHtml(q,ans){const rec=recurrence(q),r=reviewFor(q),exp=usefulExplanation(q),marked=q.options[ans.choice],correct=q.options[q.correct],cause=ans.cause;let diagnosis='Classifique a causa do erro para o reforço ficar correto.';if(cause==='knowledge')diagnosis='Falha principal: a regra não estava recuperável. Releia apenas a regra-base abaixo, feche o texto e explique com tuas palavras antes da próxima questão.';if(cause==='confusion')diagnosis='Falha principal: dois institutos/requisitos foram misturados. Compare o requisito que muda entre a alternativa marcada e a correta.';if(cause==='reading')diagnosis='Falha principal: leitura/atenção. Na próxima, leia primeiro o comando e procure palavras como NÃO, EXCETO, prazo, competência, legitimidade e efeito.';return `<div class="question-feedback ${ans.correct?'':'bad'}"><h4>${ans.correct?'Correto.':'Errado.'} Gabarito ${String.fromCharCode(65+q.correct)}.</h4><p><b>Conceito:</b> ${topicLabel(q)}</p>${!ans.correct?`<p><b>Tua alternativa:</b> ${marked}</p><p><b>Alternativa correta:</b> ${correct}</p>`:''}${exp?`<p><b>Comentário:</b> ${exp}</p>`:''}<div class="rule-box"><b>Base jurídica:</b> ${sourceBase(q)}<br><b>Regra para recuperar:</b> ${exp||'Reconstitua a regra a partir da alternativa correta e identifique sujeito, requisito, exceção, prazo/competência e efeito jurídico que a FGV alterou no distrator.'}<br><b>Reincidência:</b> ${rec.qWrong} erro(s) nesta questão • ${rec.cWrong} erro(s) neste conceito${r?` • próxima revisão ${dueLabel(r.due)}`:''}.</div>${!ans.correct?`<div class="feedback-tools"><p>${diagnosis}</p><div class="cause-buttons"><button class="btn secondary ${cause==='knowledge'?'active':''}" data-cause="knowledge">Não sabia a regra</button><button class="btn secondary ${cause==='confusion'?'active':''}" data-cause="confusion">Confundi conceitos</button><button class="btn secondary ${cause==='reading'?'active':''}" data-cause="reading">Leitura/atenção</button></div><div class="actions-row"><button class="btn primary" id="reinforceNow">Outra do mesmo conceito</button><a class="btn secondary" href="materiais.html?subject=${encodeURIComponent(canon(q.subject))}&q=${encodeURIComponent(topicLabel(q))}">Abrir videoaulas</a><a class="btn secondary" href="caderno.html?subject=${encodeURIComponent(canon(q.subject))}">Anotar regra</a></div></div>`:''}</div>`;}
function renderQuestion(){if(!session)return;const q=session.qs[session.index],ans=session.answers[q.id];$('sessionModeLabel').textContent=session.mode.toUpperCase();$('sessionProgress').textContent=`Questão ${session.index+1} de ${session.qs.length}`;$('sessionDots').innerHTML=session.qs.map((x,i)=>`<button class="${i===session.index?'active':''} ${session.answers[x.id]?'done':''}" data-qindex="${i}">${i+1}</button>`).join('');$$('[data-qindex]').forEach(b=>b.onclick=()=>{session.index=+b.dataset.qindex;session.questionStartedAt=now();renderQuestion();});$('questionSubjectLabel').textContent=subj(canon(q.subject)).name;$('questionTopicLabel').textContent=topicLabel(q);$('questionText').textContent=q.text;$('answerList').innerHTML=q.options.map((o,i)=>{let cls='';if(ans){if(i===q.correct)cls='correct';else if(i===ans.choice)cls='wrong';}return `<button class="answer-option ${cls}" data-answer="${i}" ${ans?'disabled':''}><b>${String.fromCharCode(65+i)})</b> ${o}</button>`}).join('');$$('[data-answer]').forEach(b=>b.onclick=()=>answerQuestion(+b.dataset.answer));$('feedbackBox').className=ans?'':'hidden';$('feedbackBox').innerHTML=ans?feedbackHtml(q,ans):'';$$('[data-cause]').forEach(b=>b.onclick=()=>classifyCause(b.dataset.cause));const rb=$('reinforceNow');if(rb)rb.onclick=addReinforcement;$('prevQuestion').disabled=session.index===0;$('nextQuestion').textContent=session.index===session.qs.length-1?'Finalizar':'Próxima →';}
function nextQuestion(){if(!session)return;if(session.index===session.qs.length-1){finishSession();return;}session.index++;session.questionStartedAt=now();renderQuestion();}
function finishSession(){if(!session)return;clearInterval(timer);const a=Object.values(session.answers),total=a.length,correct=a.filter(x=>x.correct).length,duration=now()-session.startedAt;state.sessions.unshift({id:`s-${now()}`,mode:session.mode,total,correct,duration,ts:now()});state.sessions=state.sessions.slice(0,50);persist();$('sessionArea').classList.add('hidden');$('sessionResult').classList.remove('hidden');$('sessionResult').innerHTML=`<p class="eyebrow">BLOCO CONCLUÍDO</p><h2>${correct}/${total} acertos</h2><p class="muted">Erros, causas e revisões foram incorporados ao sistema.</p><div class="actions-row"><button class="btn primary" id="newAdaptive">Novo adaptativo</button><button class="btn secondary" id="goErrors">Ver erros</button></div>`;$('newAdaptive').onclick=()=>{resetSession();startSession('adaptive');};$('goErrors').onclick=()=>{resetSession();page('errors');};session=null;renderAll();}
function resetSession(){$('sessionSetup').classList.remove('hidden');$('sessionArea').classList.add('hidden');$('sessionResult').classList.add('hidden');}

function errorRows(){return Object.values(state.reviews).map(r=>{const q=qById(r.qid);if(!q)return null;const a=state.attempts.filter(x=>x.qid===r.qid),wrong=a.filter(x=>!x.correct).length,conceptWrong=attemptsForConcept(q).filter(x=>!x.correct).length;return {...r,q,wrong,total:a.length,conceptWrong,recurrent:wrong>=2||conceptWrong>=2||(r.lapses||0)>=2};}).filter(Boolean);}
function renderErrors(){const all=errorRows(),open=all.filter(x=>!x.mastered),due=open.filter(x=>x.due<=now()),rec=open.filter(x=>x.recurrent),noCause=open.filter(x=>!x.cause);$('errOpen').textContent=open.length;$('errDue').textContent=due.length;$('errRecurrent').textContent=rec.length;$('errNoCause').textContent=noCause.length;const subject=$('errorSubject').value,cause=$('errorCause').value,status=$('errorStatus').value,q=String($('errorSearch').value||'').toLowerCase();let rows=all.filter(x=>status==='all'||(status==='open'&&!x.mastered)||(status==='due'&&!x.mastered&&x.due<=now())||(status==='recurrent'&&!x.mastered&&x.recurrent));if(subject!=='all')rows=rows.filter(x=>canon(x.subject)===subject);if(cause!=='all')rows=rows.filter(x=>cause==='none'?!x.cause:x.cause===cause);if(q)rows=rows.filter(x=>`${topicLabel(x.q)} ${x.q.text} ${subj(canon(x.subject)).name}`.toLowerCase().includes(q));rows.sort((a,b)=>(b.recurrent?1:0)-(a.recurrent?1:0)||(a.due<=now()?0:1)-(b.due<=now()?0:1)||b.wrong-a.wrong);$('errorList').innerHTML=rows.length?rows.slice(0,60).map(x=>`<article class="err ${x.recurrent?'recurrent':''}"><div><h4>${subj(canon(x.subject)).name} • ${topicLabel(x.q)}</h4><p>${x.q.text}</p><div class="badges"><span class="pill ${x.recurrent?'bad':''}">${x.wrong} erro(s) na questão</span><span class="pill ${x.conceptWrong>=2?'bad':''}">${x.conceptWrong} erro(s) no conceito</span><span class="pill ${x.due<=now()?'warn':''}">${x.mastered?'dominado':dueLabel(x.due)}</span><span class="pill">${x.cause==='knowledge'?'não sabia a regra':x.cause==='confusion'?'confusão conceitual':x.cause==='reading'?'leitura/atenção':'causa não classificada'}</span></div><div class="rule-box"><b>Base de revisão:</b> ${sourceBase(x.q)}<br><b>Conceito:</b> ${topicLabel(x.q)}${usefulExplanation(x.q)?`<br><b>Regra:</b> ${usefulExplanation(x.q)}`:''}</div></div><div class="err-actions"><button class="btn primary" data-review-q="${x.q.id}">Revisar agora</button><button class="btn secondary" data-topic-q="${x.q.id}">Treinar conceito</button><a class="btn secondary" href="materiais.html?subject=${encodeURIComponent(canon(x.subject))}&q=${encodeURIComponent(topicLabel(x.q))}">Videoaula</a></div></article>`).join(''):'<div class="muted">Nenhum erro neste filtro.</div>';$$('[data-review-q]').forEach(b=>b.onclick=()=>startCustomReview(b.dataset.reviewQ));$$('[data-topic-q]').forEach(b=>b.onclick=()=>startTopicBlock(b.dataset.topicQ));renderConcepts();renderErrorCauseSummary();}
function startCustomReview(id){const q=qById(id);if(!q)return;session={mode:'review',qs:[q],index:0,answers:{},startedAt:now(),questionStartedAt:now()};$('sessionSetup').classList.add('hidden');$('sessionResult').classList.add('hidden');$('sessionArea').classList.remove('hidden');page('questions');startTimer();renderQuestion();}
function startTopicBlock(id){const q=qById(id);if(!q)return;const key=conceptKeyQ(q);let qs=QUESTIONS.filter(x=>conceptKeyQ(x)===key);qs=uniqueFamilies(qs).sort(()=>Math.random()-.5).slice(0,5);if(!qs.length){notice('Não há questões suficientes deste conceito.');return;}session={mode:'reinforcement',qs,index:0,answers:{},startedAt:now(),questionStartedAt:now()};$('sessionSetup').classList.add('hidden');$('sessionResult').classList.add('hidden');$('sessionArea').classList.remove('hidden');page('questions');startTimer();renderQuestion();}
function renderConcepts(){const groups=new Map();for(const a of state.attempts){const sid=canon(a.subject),t=INTEL?.resolveTopic(sid,a.topic),key=`${sid}|${t?.id||a.topic||'geral'}`,g=groups.get(key)||{sid,label:t?.label||a.topic||'Geral',n:0,wrong:0,knowledge:0,confusion:0,reading:0};g.n++;if(!a.correct){g.wrong++;if(a.cause)g[a.cause]++;}groups.set(key,g);}const rows=[...groups.values()].filter(g=>g.wrong).sort((a,b)=>b.wrong-a.wrong).slice(0,12);$('conceptSummary').innerHTML=rows.length?rows.map(g=>`<div class="concept-row"><div><strong>${subj(g.sid).name} • ${g.label}</strong><small>${g.wrong} erro(s) em ${g.n} tentativa(s)</small></div><b>${Math.round((1-g.wrong/g.n)*100)}%</b><a class="mini-link" href="materiais.html?subject=${encodeURIComponent(g.sid)}&q=${encodeURIComponent(g.label)}">aula</a></div>`).join(''):'<div class="muted">Os conceitos aparecem aqui conforme os erros forem registrados.</div>';}
function renderErrorCauseSummary(){const wrong=state.attempts.filter(a=>!a.correct),c={knowledge:0,confusion:0,reading:0,none:0};wrong.forEach(a=>a.cause?c[a.cause]++:c.none++);const total=wrong.length||1;$('errorCauseSummary').innerHTML=`<div class="cause-card"><strong>${c.knowledge}</strong><span>Não sabia a regra • ${Math.round(c.knowledge/total*100)}%</span></div><div class="cause-card"><strong>${c.confusion}</strong><span>Confusão conceitual • ${Math.round(c.confusion/total*100)}%</span></div><div class="cause-card"><strong>${c.reading}</strong><span>Leitura/atenção • ${Math.round(c.reading/total*100)}%</span></div><div class="cause-card"><strong>${c.none}</strong><span>Sem classificação • ${Math.round(c.none/total*100)}%</span></div>`;}
function renderAnalytics(){const rows=SUBJECTS.map(s=>({s,st:stats(s.id)}));$('analyticsBody').innerHTML=rows.map(x=>`<tr><td><strong>${x.s.name}</strong></td><td>${x.s.q}/80</td><td>${x.st.n}</td><td>${x.st.n?pct(x.st.raw):'—'}</td><td>${pct(x.st.estimated)}</td><td>${x.st.wrong||0}</td></tr>`).join('');const c={knowledge:0,confusion:0,reading:0,none:0};state.attempts.filter(a=>!a.correct).forEach(a=>a.cause?c[a.cause]++:c.none++);$('causeBreakdown').innerHTML=`<div class="cause-card"><strong>${c.knowledge}</strong><span>Não sabia a regra</span></div><div class="cause-card"><strong>${c.confusion}</strong><span>Confusão conceitual</span></div><div class="cause-card"><strong>${c.reading}</strong><span>Leitura/atenção</span></div><div class="cause-card"><strong>${c.none}</strong><span>Sem classificação</span></div>`;}
function renderAll(){renderDashboard();renderPlan();renderStudy();renderErrors();renderAnalytics();}

function bind(){$$('[data-page]').forEach(b=>b.onclick=()=>page(b.dataset.page));$$('[data-go-page]').forEach(b=>b.onclick=()=>page(b.dataset.goPage));$('quickStudy').onclick=()=>startSession('adaptive');$('heroAdaptive').onclick=()=>startSession('adaptive');$('routineStart').onclick=()=>startSession('adaptive');$('quickReview').onclick=()=>page('errors');$('heroErrors').onclick=()=>page('errors');$('startDueReview').onclick=()=>startSession('review',10,'all');$('savePlan').onclick=()=>{state.profile.targetDate=$('targetDate').value||readCal().exam;state.profile.targetScore=clamp(Number($('targetScore').value||45),40,70);state.profile.dailyMinutes=clamp(Number($('dailyMinutes').value||60),20,300);state.profile.strategy=$('strategy').value;persist();renderAll();notice('Plano atualizado.');};$('saveCalendar').onclick=()=>{const c={edital:$('calEdital').value||OFFICIAL_CAL.edital,open:$('calOpen').value||OFFICIAL_CAL.open,close:$('calClose').value||OFFICIAL_CAL.close,exam:$('calExam').value||OFFICIAL_CAL.exam};localStorage.setItem(CAL_KEY,JSON.stringify(c));state.profile.targetDate=c.exam;persist();renderAll();notice('Calendário atualizado.');};$$('[data-subject-filter]').forEach(b=>b.onclick=()=>{state.settings.subjectFilter=b.dataset.subjectFilter;persist();$$('[data-subject-filter]').forEach(x=>x.classList.toggle('active',x===b));renderStudy();});$('trainSubject').onclick=()=>startSession('adaptive',10,selectedSubject);$$('[data-mode]').forEach(b=>b.onclick=()=>{selectedMode=b.dataset.mode;$$('[data-mode]').forEach(x=>x.classList.toggle('active',x===b));});$('startSession').onclick=()=>startSession(selectedMode,Number($('questionLimit').value),$('questionSubject').value);$('prevQuestion').onclick=()=>{if(session&&session.index>0){session.index--;session.questionStartedAt=now();renderQuestion();}};$('nextQuestion').onclick=nextQuestion;$('finishSession').onclick=finishSession;['errorSearch','errorSubject','errorCause','errorStatus'].forEach(id=>$(id).addEventListener(id==='errorSearch'?'input':'change',renderErrors));}

async function bootstrap(){try{const imported=await getAllQuestions();const map=new Map(BUILTIN.map(q=>[q.id,q]));imported.forEach(q=>map.set(q.id,q));QUESTIONS=[...map.values()];}catch(e){console.warn('Banco ampliado indisponível; usando base local.',e);QUESTIONS=[...BUILTIN];}renderQuestionSelectors();bind();renderAll();if(INTEL?.EXAM?.status==='awaiting-48-edital')notice('48º EOU: edital previsto para 21/09/2026; calendário oficial pode ser ajustado se a OAB alterar as datas.');}
bootstrap();