import { initializeApp, getApps } from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-app.js';
import { getAuth, GoogleAuthProvider, signInWithPopup, signOut, onAuthStateChanged } from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-auth.js';
import { getFirestore, doc, getDoc, setDoc } from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-firestore.js';
import { getAllQuestions } from './question-bank.js';

const $=id=>document.getElementById(id);
const K='oab-aprova-notebook-v1',MAIN='oab-aprova-premium-v1',DAY=86400000;
const S=window.OAB_SUBJECTS||[],I=window.OAB_INTELLIGENCE||null;
let data=load(),selected=data.selected||'etica',questions=[...(window.OAB_QUESTIONS||[])],currentUser=null,auth=null,db=null,cloudTimer=null,noteTimer=null;

function base(){return {version:2,notes:{},cards:[],selected:'etica',updatedAt:Date.now()};}
function normalize(v){const b=base(),d={...b,...(v||{})};d.notes=d.notes&&typeof d.notes==='object'?d.notes:{};d.cards=Array.isArray(d.cards)?d.cards:[];return d;}
function load(){try{return normalize(JSON.parse(localStorage.getItem(K)||'null'));}catch{return base();}}
function save({cloud=true}={}){data.selected=selected;data.updatedAt=Date.now();localStorage.setItem(K,JSON.stringify(data));$('saved').textContent='salvo agora';if(cloud&&currentUser&&db){clearTimeout(cloudTimer);cloudTimer=setTimeout(async()=>{try{await setDoc(doc(db,'users',currentUser.uid,'notebook','main'),data);$('syncStatus').textContent='Caderno sincronizado com a nuvem.';}catch{$('syncStatus').textContent='Salvo localmente • nuvem indisponível.';}},600);}renderMetrics();}
function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function main(){try{return JSON.parse(localStorage.getItem(MAIN)||'{}')}catch{return {}}}
function subName(id){return S.find(s=>s.id===id)?.name||I?.SUBJECTS?.[id]?.name||id;}
function causeLabel(c){return c==='knowledge'?'Regra desconhecida':c==='confusion'?'Confusão conceitual':c==='reading'?'Leitura/atenção':'Não classificado';}
function dueLabel(ts){const d=Math.ceil((Number(ts||0)-Date.now())/DAY);return d<=0?'vencido':d===1?'amanhã':`em ${d} dias`;}

function renderSubjects(){$('subjects').innerHTML=S.map(s=>`<button class="sub ${s.id===selected?'active':''}" data-sub="${s.id}">${esc(s.name)}</button>`).join('');document.querySelectorAll('[data-sub]').forEach(b=>b.onclick=()=>{selected=b.dataset.sub;render();});}
function renderPriority(){const st=main();if(!I){$('priorityTopic').textContent='Diagnóstico';$('priorityReason').textContent='Resolva questões para o motor formar prioridade.';return;}try{const x=I.rankTopics(st,{subject:selected})[0];if(!x)return;$('priorityTopic').textContent=x.topic.label;$('priorityReason').textContent=I.explainRecommendation(x);$('trainPriority').href=`questao-guiada.html?subject=${encodeURIComponent(selected)}&topic=${encodeURIComponent(x.topic.id)}&priority=adaptive&origin=official`;}catch{$('priorityTopic').textContent='Diagnóstico';}}
function renderMetrics(){const st=main(),revs=Object.values(st.reviews||{}).filter(r=>r.subject===selected&&!r.mastered),due=revs.filter(r=>Number(r.due||0)<=Date.now()).length,cards=data.cards.filter(c=>c.subject===selected&&!c.mastered&&Number(c.due||0)<=Date.now()).length;const causes={knowledge:0,confusion:0,reading:0};revs.forEach(r=>{if(r.cause)causes[r.cause]=(causes[r.cause]||0)+1;});const top=Object.entries(causes).sort((a,b)=>b[1]-a[1])[0];$('mOpen').textContent=revs.length;$('mDue').textContent=due;$('mCards').textContent=cards;$('mCause').textContent=top&&top[1]?causeLabel(top[0]):'—';}

function reviewCard(id,correct){const c=data.cards.find(x=>x.id===id);if(!c)return;if(!correct){c.streak=0;c.mastered=false;c.due=Date.now()+DAY;c.lastSeen=Date.now();}else{const intervals=[3,7,14,30,60],streak=(c.streak||0)+1,interval=intervals[Math.min(streak-1,intervals.length-1)];c.streak=streak;c.due=Date.now()+interval*DAY;c.mastered=streak>=4;c.lastSeen=Date.now();}save();renderCards();}
function renderCards(){const cards=data.cards.filter(c=>c.subject===selected).sort((a,b)=>Number(a.due||0)-Number(b.due||0));$('cards').innerHTML=cards.length?cards.map(c=>`<div class="flash ${Number(c.due||0)<=Date.now()&&!c.mastered?'due':''}" data-card="${esc(c.id)}"><strong>${esc(c.front)}</strong><div class="flash-meta"><span class="pill ${c.mastered?'good':Number(c.due||0)<=Date.now()?'bad':'warn'}">${c.mastered?'dominado':dueLabel(c.due)}</span><span class="pill">sequência ${c.streak||0}</span></div><div class="back">${esc(c.back)}<div class="row" style="margin-top:10px"><button class="btn secondary" data-card-wrong="${esc(c.id)}">Errei</button><button class="btn primary" data-card-right="${esc(c.id)}">Acertei</button><button class="text-btn" data-del="${esc(c.id)}">Excluir</button></div></div></div>`).join(''):'<p class="muted">Nenhum flashcard nesta matéria.</p>';document.querySelectorAll('[data-card]').forEach(c=>c.onclick=e=>{if(e.target.closest('button'))return;c.classList.toggle('open');});document.querySelectorAll('[data-card-wrong]').forEach(b=>b.onclick=e=>{e.stopPropagation();reviewCard(b.dataset.cardWrong,false);});document.querySelectorAll('[data-card-right]').forEach(b=>b.onclick=e=>{e.stopPropagation();reviewCard(b.dataset.cardRight,true);});document.querySelectorAll('[data-del]').forEach(b=>b.onclick=e=>{e.stopPropagation();data.cards=data.cards.filter(c=>c.id!==b.dataset.del);save();renderCards();});}
function cardFromReview(q,r){if(!q)return;const exists=data.cards.some(c=>c.sourceQid===q.id);if(exists){alert('Esse erro já virou flashcard.');return;}data.cards.push({id:'c-'+Date.now(),subject:r.subject,front:`Qual regra resolve esta situação? ${q.text}`,back:q.explanation||'Recupere a regra central e a exceção decisiva.',createdAt:Date.now(),due:Date.now(),streak:0,mastered:false,sourceQid:q.id});save();renderCards();}
function renderErrors(){const st=main(),revs=Object.values(st.reviews||{}).filter(r=>r.subject===selected&&!r.mastered).sort((a,b)=>Number(a.due||0)-Number(b.due||0)).slice(0,30);$('errors').innerHTML=revs.length?revs.map(r=>{const q=questions.find(x=>x.id===r.qid);return `<div class="flash error"><strong>${esc(r.topic||'Erro')}</strong><div class="flash-meta"><span class="pill bad">${esc(causeLabel(r.cause))}</span><span class="pill ${Number(r.due||0)<=Date.now()?'bad':'warn'}">${esc(dueLabel(r.due))}</span></div><p>${esc(q?.text||'Questão registrada no caderno de erros.')}</p><div class="back">${esc(q?.explanation||'Reveja o fundamento e escreva a regra em uma frase.')}</div><div class="active-actions">${q?`<button class="btn secondary" data-make-card="${esc(r.qid)}">Virar flashcard</button>`:''}<a class="btn primary" href="questao-guiada.html?subject=${encodeURIComponent(r.subject)}&topic=${encodeURIComponent(r.topic||'')}&priority=adaptive&origin=official">Treinar este tema</a></div></div>`}).join(''):'<p class="muted">Nenhum erro aberto desta matéria.</p>';document.querySelectorAll('[data-make-card]').forEach(b=>b.onclick=()=>{const r=revs.find(x=>x.qid===b.dataset.makeCard),q=questions.find(x=>x.id===b.dataset.makeCard);cardFromReview(q,r);});}
function render(){const s=S.find(x=>x.id===selected)||S[0];$('title').textContent=s?.name||selected;$('notes').value=data.notes[selected]||'';renderSubjects();renderPriority();renderCards();renderErrors();renderMetrics();save({cloud:false});}

$('notes').oninput=()=>{clearTimeout(noteTimer);noteTimer=setTimeout(()=>{data.notes[selected]=$('notes').value;save();},500);};
$('saveNote').onclick=()=>{data.notes[selected]=$('notes').value;save();};
$('addCard').onclick=()=>{const text=$('notes'),sel=text.value.slice(text.selectionStart,text.selectionEnd).trim(),front=prompt('Frente do flashcard:',sel||'Qual é a regra?');if(!front)return;const back=prompt('Verso / resposta:',sel||'');if(!back)return;data.cards.push({id:'c-'+Date.now(),subject:selected,front,back,createdAt:Date.now(),due:Date.now(),streak:0,mastered:false});save();renderCards();};
$('export').onclick=()=>{const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='oab-aprova-caderno.json';a.click();URL.revokeObjectURL(a.href);};

async function initFirebase(){try{const app=getApps()[0]||initializeApp(window.OAB_FIREBASE_CONFIG);auth=getAuth(app);db=getFirestore(app);onAuthStateChanged(auth,async user=>{currentUser=user;$('loginGoogle').classList.toggle('hidden',!!user);$('logoutGoogle').classList.toggle('hidden',!user);if(!user){$('syncStatus').textContent='Caderno salvo neste navegador.';return;}$('syncStatus').textContent='Sincronizando caderno…';try{const ref=doc(db,'users',user.uid,'notebook','main'),snap=await getDoc(ref);if(snap.exists()&&Number(snap.data()?.updatedAt||0)>Number(data.updatedAt||0)){data=normalize(snap.data());selected=data.selected||selected;localStorage.setItem(K,JSON.stringify(data));render();}else await setDoc(ref,data);$('syncStatus').textContent='Caderno sincronizado com a nuvem.';}catch{$('syncStatus').textContent='Conta conectada • caderno local.';}});$('loginGoogle').onclick=()=>signInWithPopup(auth,new GoogleAuthProvider()).catch(()=>{});$('logoutGoogle').onclick=()=>signOut(auth);}catch{$('syncStatus').textContent='Caderno local • Firebase indisponível.';}}

try{const imported=await getAllQuestions();const m=new Map(questions.map(q=>[q.id,q]));imported.forEach(q=>m.set(q.id,q));questions=[...m.values()];}catch{}
render();initFirebase();
