const SOURCES = {
  etica:{title:'Lei 8.906/1994 e normas da OAB',url:'https://www.planalto.gov.br/ccivil_03/leis/l8906.htm'},
  constitucional:{title:'Constituição da República Federativa do Brasil',url:'https://www.planalto.gov.br/ccivil_03/constituicao/constituicao.htm'},
  tributario:{title:'Código Tributário Nacional',url:'https://www.planalto.gov.br/ccivil_03/leis/l5172compilado.htm'},
  administrativo:{title:'Constituição, Lei 14.133/2021 e legislação administrativa',url:'https://www.planalto.gov.br/ccivil_03/_ato2019-2022/2021/lei/l14133.htm'},
  civil:{title:'Código Civil',url:'https://www.planalto.gov.br/ccivil_03/leis/2002/l10406compilada.htm'},
  'processo-civil':{title:'Código de Processo Civil',url:'https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2015/lei/l13105.htm'},
  penal:{title:'Código Penal',url:'https://www.planalto.gov.br/ccivil_03/decreto-lei/del2848compilado.htm'},
  'processo-penal':{title:'Código de Processo Penal',url:'https://www.planalto.gov.br/ccivil_03/decreto-lei/del3689compilado.htm'},
  trabalho:{title:'Consolidação das Leis do Trabalho',url:'https://www.planalto.gov.br/ccivil_03/decreto-lei/del5452compilado.htm'},
  'processo-trabalho':{title:'Consolidação das Leis do Trabalho — Processo do Trabalho',url:'https://www.planalto.gov.br/ccivil_03/decreto-lei/del5452compilado.htm'},
  empresarial:{title:'Código Civil e Lei 11.101/2005',url:'https://www.planalto.gov.br/ccivil_03/_ato2004-2006/2005/lei/l11101.htm'}
};

// Matriz autoral de regras jurídicas. Cada regra gera cinco casos de superfície diferentes,
// mas o sistema preserva ruleId para não servir duas variantes do mesmo ponto no mesmo bloco.
const RULES = [
  // ÉTICA PROFISSIONAL
  ['eti-r01','etica','Honorários','Uma cliente contratou advogado por honorários convencionais e venceu a ação, havendo também condenação da parte contrária em honorários de sucumbência.','Os honorários de sucumbência pertencem ao advogado e podem coexistir com os honorários contratuais.','Os honorários de sucumbência pertencem sempre à cliente e substituem os contratuais.','A existência de contrato escrito impede honorários de sucumbência.','Os honorários de sucumbência só pertencem ao advogado se houver cláusula expressa no contrato.','Honorários convencionados e sucumbenciais têm fundamentos distintos; a sucumbência é direito do advogado.','Estatuto da Advocacia, regime dos honorários'],
  ['eti-r02','etica','Incompatibilidade e impedimento','Um bacharel inscrito na OAB assume cargo que a lei considera incompatível com a advocacia e pretende continuar atuando apenas em causas particulares.','A incompatibilidade impede totalmente o exercício da advocacia enquanto perdurar a situação.','A incompatibilidade apenas impede atuação contra o ente público que remunera o advogado.','A incompatibilidade limita somente a atuação criminal.','A incompatibilidade não afeta a advocacia privada sem vínculo com o cargo.','Incompatibilidade gera proibição total; impedimento é a restrição parcial ao exercício profissional.','Estatuto da Advocacia, incompatibilidades e impedimentos'],
  ['eti-r03','etica','Publicidade','Uma advogada pretende impulsionar conteúdo jurídico informativo em rede social, sem promessa de resultado, divulgação de preço ou captação indevida.','A divulgação pode ser admitida se permanecer informativa, discreta e sem mercantilização ou captação de clientela.','Todo impulsionamento digital é absolutamente proibido à advocacia.','A publicidade é livre desde que o advogado não mencione o próprio nome.','A publicidade só é possível após autorização individual do Tribunal de Ética.','A publicidade advocatícia admite meios digitais, mas continua submetida à sobriedade, informação e vedação à captação indevida.','Estatuto, Código de Ética e Provimento sobre publicidade'],
  ['eti-r04','etica','Renúncia ao mandato','Um advogado renuncia ao mandato e comunica formalmente o cliente, que ainda não constituiu novo patrono.','O advogado deve continuar representando o cliente pelo período legal após a notificação, salvo substituição anterior.','A renúncia extingue imediatamente toda responsabilidade processual no instante do envio da mensagem.','O advogado só pode renunciar com autorização judicial.','A renúncia é inválida se não houver concordância expressa do cliente.','A renúncia é ato unilateral, mas a lei preserva por período limitado a representação para evitar abandono da defesa.','Estatuto da Advocacia, mandato e renúncia'],
  ['eti-r05','etica','Prerrogativas','Durante investigação já documentada, o defensor constituído pede acesso aos elementos de prova existentes que interessem ao exercício da defesa.','O acesso aos elementos já documentados integra as prerrogativas da defesa, ressalvado o sigilo necessário de diligências em andamento.','Todo inquérito é absolutamente inacessível à defesa até o oferecimento da denúncia.','O defensor só pode examinar autos mediante autorização do Ministério Público.','O acesso depende sempre de decisão judicial individualizada.','A defesa deve conhecer os elementos já documentados relevantes, sem comprometer diligências sigilosas em curso.','Estatuto da Advocacia e prerrogativas profissionais'],
  ['eti-r06','etica','Sociedade de advocacia','Dois advogados pretendem constituir sociedade profissional e incluir atividade empresarial estranha à advocacia como objeto social principal.','A sociedade de advocacia deve ter objeto profissional compatível com a advocacia e não pode assumir caráter mercantil estranho à profissão.','A sociedade de advocacia pode explorar qualquer atividade empresarial desde que um dos sócios seja advogado.','A sociedade pode adotar livremente natureza mercantil e captar investimentos de não advogados.','A atividade jurídica precisa ser apenas secundária, pois a sociedade deve ter objeto comercial mais amplo.','A disciplina própria da sociedade de advocacia preserva sua natureza profissional e veda mercantilização incompatível.','Estatuto da Advocacia, sociedades de advogados'],
  ['eti-r07','etica','Sigilo profissional','Um advogado recebe informação confidencial do cliente no exercício profissional e é pressionado por terceiro a divulgá-la sem autorização ou justa causa.','O sigilo profissional é dever do advogado e, em regra, impede a divulgação da informação recebida no exercício da profissão.','O sigilo existe apenas se houver cláusula contratual específica.','O advogado pode divulgar informações do cliente sempre que considerar interessante à própria defesa comercial.','O dever de sigilo termina automaticamente com o encerramento do processo.','O sigilo profissional é dever ético autônomo e persiste para além da relação processual, ressalvadas hipóteses juridicamente justificadas.','Código de Ética e disciplina do sigilo profissional'],
  ['eti-r08','etica','Prestação de contas','Após receber valores em nome do cliente, o advogado encerra a demanda e pretende reter o numerário sem apresentar discriminação.','O advogado deve prestar contas ao cliente e dar destinação juridicamente adequada aos valores recebidos em razão do mandato.','A prestação de contas é facultativa quando o resultado do processo foi favorável.','Os valores recebidos em nome do cliente passam automaticamente ao patrimônio do advogado.','A prestação de contas somente pode ser exigida judicialmente depois de cinco anos.','O mandato e a ética profissional impõem transparência e prestação de contas sobre valores recebidos por conta do cliente.','Estatuto e Código de Ética, prestação de contas'],
  ['eti-r09','etica','Captação de clientela','Um escritório oferece comissão a terceiros sem vínculo profissional por cada pessoa encaminhada que contrate serviços jurídicos.','A prática caracteriza captação ou mercantilização incompatível com as regras éticas da advocacia.','A prática é válida se a comissão não superar dez por cento dos honorários.','A captação é permitida desde que o terceiro não seja advogado.','A conduta é livre quando o cliente assina declaração de ciência.','A advocacia não pode ser comercializada mediante intermediação remunerada destinada à captação de clientela.','Código de Ética e regras de publicidade e captação'],
  ['eti-r10','etica','Pro bono','Uma advogada deseja prestar assistência jurídica gratuita a pessoa sem recursos, sem finalidade eleitoral e sem usar a gratuidade como publicidade para captar clientes.','A advocacia pro bono pode ser compatível com a ética quando observadas as regras profissionais e ausente finalidade de captação ou promoção indevida.','A advocacia gratuita é sempre proibida porque todo serviço jurídico deve ser remunerado.','O trabalho pro bono só pode ser feito por defensor público.','A prestação gratuita autoriza publicidade ostensiva com promessa de atendimento ilimitado.','A gratuidade não é, por si, infração ética; o problema surge quando usada para mercantilização, captação ou finalidades incompatíveis.','Código de Ética, advocacia pro bono'],

  // CONSTITUCIONAL
  ['con-r01','constitucional','Remédios constitucionais','Uma pessoa pretende conhecer e, se necessário, retificar informação a seu respeito existente em banco de dados de caráter público.','O habeas data é o instrumento constitucional vocacionado ao conhecimento e à retificação de dados pessoais em registros públicos ou de caráter público.','O habeas corpus é o remédio próprio para qualquer dado cadastral incorreto.','A ação popular substitui o habeas data quando o registro pertence ao Estado.','O mandado de injunção é a via destinada à retificação de banco de dados pessoal.','O habeas data tutela especificamente acesso e correção de dados pessoais nas hipóteses constitucionais.','Constituição Federal, art. 5º, LXXII'],
  ['con-r02','constitucional','Mandado de injunção','A falta de norma regulamentadora torna inviável o exercício de direito ou liberdade constitucional por determinado titular.','Pode ser cabível mandado de injunção para enfrentar a omissão normativa que inviabiliza o exercício do direito constitucional.','A única via possível é ação popular, independentemente da natureza da omissão.','O mandado de injunção exige sempre ameaça à liberdade de locomoção.','A omissão legislativa nunca pode ser objeto de tutela judicial.','O mandado de injunção tutela situações em que a falta de regulamentação impede o exercício de direito constitucional.','Constituição Federal, art. 5º, LXXI'],
  ['con-r03','constitucional','Controle de constitucionalidade','Lei estadual posterior à Constituição é questionada diretamente perante o STF por incompatibilidade com a Constituição Federal.','Em tese, a lei estadual pode ser objeto de ação direta de inconstitucionalidade perante o STF.','A ADI no STF só alcança leis federais.','Lei estadual somente pode ser questionada em habeas corpus.','O STF não exerce controle abstrato de lei estadual em face da Constituição Federal.','A Constituição atribui ao STF controle abstrato de lei ou ato normativo federal ou estadual em face da Constituição Federal.','Constituição Federal, art. 102, I, a'],
  ['con-r04','constitucional','ADC','Pretende-se obter pronunciamento abstrato do STF sobre a constitucionalidade de lei federal cuja aplicação vem gerando controvérsia judicial relevante.','A ação declaratória de constitucionalidade é instrumento de controle concentrado que tem por objeto lei ou ato normativo federal.','A ADC pode ter como objeto originário qualquer lei municipal.','A ADC somente pode discutir lei estadual.','A ADC é recurso cabível apenas depois do trânsito em julgado de ação individual.','A ADC integra o controle concentrado e possui objeto federal, conforme desenho constitucional.','Constituição Federal, art. 102, I, a'],
  ['con-r05','constitucional','Lei municipal e STF','Uma lei municipal é apontada como incompatível diretamente com a Constituição Federal e alguém pretende ajuizar ADI no STF contra ela.','A lei municipal não é objeto de ADI originária no STF em face direta da Constituição Federal.','Toda lei municipal pode ser impugnada por ADI no STF exatamente como lei federal.','A competência para ADI de lei municipal em face da Constituição Federal é sempre do STJ.','A única forma de controle de lei municipal é por decreto legislativo.','O modelo constitucional da ADI no STF abrange lei federal ou estadual; a lei municipal segue outras vias de controle.','Constituição Federal, art. 102, I, a'],
  ['con-r06','constitucional','Direitos fundamentais','Órgão público sustenta que uma garantia fundamental não produz qualquer efeito enquanto não houver lei ordinária específica.','As normas definidoras de direitos e garantias fundamentais têm aplicação imediata, sem excluir hipóteses em que a regulamentação seja necessária para sua plena concretização.','Nenhum direito fundamental produz efeitos antes de lei ordinária.','Direitos fundamentais vinculam apenas particulares e não o Poder Público.','Toda garantia fundamental pode ser abolida por lei ordinária posterior.','A Constituição estabelece aplicação imediata dos direitos e garantias fundamentais.','Constituição Federal, art. 5º, §1º'],
  ['con-r07','constitucional','Tratados de direitos humanos','Tratado internacional de direitos humanos é aprovado em cada Casa do Congresso, em dois turnos, por três quintos dos votos dos respectivos membros.','O tratado aprovado por esse rito é equivalente às emendas constitucionais.','Todo tratado internacional, qualquer que seja o tema e o quórum, equivale a emenda constitucional.','Tratado de direitos humanos jamais pode ter hierarquia constitucional.','O rito descrito transforma o tratado em lei complementar, sem força constitucional.','A Constituição prevê rito qualificado específico para tratados de direitos humanos com equivalência às emendas constitucionais.','Constituição Federal, art. 5º, §3º'],
  ['con-r08','constitucional','Cláusulas pétreas','Proposta de emenda constitucional pretende abolir a separação dos Poderes e os direitos e garantias individuais.','A proposta encontra limite material ao poder de reforma e não pode deliberar pela abolição das cláusulas protegidas pela Constituição.','Emenda constitucional pode abolir qualquer conteúdo se aprovada por três quintos em dois turnos.','Cláusula pétrea impede apenas alteração por lei ordinária, não por emenda.','A separação dos Poderes não recebe proteção contra emenda constitucional.','O poder constituinte derivado reformador é juridicamente limitado pelas cláusulas pétreas.','Constituição Federal, art. 60, §4º'],
  ['con-r09','constitucional','Competência concorrente','Na ausência de lei federal sobre normas gerais em matéria de competência concorrente, um Estado edita disciplina própria; depois sobrevém lei federal de normas gerais incompatível em parte.','Na ausência da lei federal, o Estado exerce competência legislativa plena; a superveniência da lei federal suspende a eficácia da lei estadual no que lhe for contrário.','A ausência de lei federal impede totalmente o Estado de legislar.','A lei estadual revoga automaticamente a futura lei federal.','A superveniência de lei federal anula integralmente a lei estadual desde a origem, mesmo nos pontos compatíveis.','A Constituição combina competência suplementar estadual, competência plena na omissão federal e suspensão de eficácia no conflito superveniente.','Constituição Federal, art. 24, §§1º a 4º'],
  ['con-r10','constitucional','Mandado de segurança','Autoridade pública pratica ato ilegal que ameaça direito líquido e certo não protegido por habeas corpus ou habeas data, e a prova necessária já está documentalmente formada.','Em tese, pode ser cabível mandado de segurança para proteger o direito líquido e certo nas condições constitucionais e legais.','O mandado de segurança só protege liberdade de locomoção.','O mandado de segurança exige sempre produção extensa de prova pericial para formação do direito.','O remédio é exclusivo para retificação de dados pessoais.','O mandado de segurança tutela direito líquido e certo não amparado por habeas corpus ou habeas data, exigindo demonstração adequada do direito.','Constituição Federal, art. 5º, LXIX'],

  // TRIBUTÁRIO
  ['tri-r01','tributario','Competência tributária','Um ente federativo pretende transferir definitivamente a uma empresa privada o poder constitucional de instituir determinado tributo.','A competência tributária é indelegável; funções administrativas de arrecadação ou fiscalização podem ser atribuídas nos limites legais, mas isso não transfere a competência constitucional.','A competência tributária pode ser vendida a empresa privada por contrato.','Qualquer particular pode instituir tributo se depois repassar a receita ao ente público.','A competência tributária se transfere automaticamente junto com a arrecadação.','O CTN distingue competência tributária, indelegável, de atribuições administrativas relacionadas à cobrança e fiscalização.','CTN, arts. 6º e 7º'],
  ['tri-r02','tributario','Suspensão da exigibilidade','Contribuinte obtém moratória validamente concedida em relação a crédito tributário já constituído.','A moratória suspende a exigibilidade do crédito tributário enquanto produzir seus efeitos.','A moratória extingue definitivamente o crédito tributário.','A moratória transforma o tributo em imunidade constitucional.','A moratória equivale sempre à remissão integral da dívida.','O CTN inclui a moratória entre as causas de suspensão da exigibilidade do crédito.','CTN, art. 151'],
  ['tri-r03','tributario','Remissão','Lei autoriza, nas condições previstas no CTN, o perdão de determinado crédito tributário já constituído.','A remissão é hipótese de extinção do crédito tributário.','A remissão apenas suspende a exigibilidade e mantém integralmente o crédito.','A remissão é modalidade de imunidade tributária.','A remissão é sinônimo de moratória.','No sistema do CTN, remissão extingue o crédito tributário, diferentemente das causas de suspensão.','CTN, art. 156'],
  ['tri-r04','tributario','Imunidade e isenção','Contribuinte confunde imunidade constitucional com isenção criada por lei ordinária.','A imunidade limita constitucionalmente o poder de tributar, enquanto a isenção decorre de norma infraconstitucional dentro de competência tributária existente.','Imunidade e isenção são expressões idênticas e sempre resultam de decreto do Executivo.','A isenção retira do ente a própria competência constitucional para instituir o tributo.','A imunidade somente pode ser criada por portaria administrativa.','Imunidade e isenção operam em planos normativos distintos: Constituição e legislação infraconstitucional.','Constituição Federal e CTN, limitações ao poder de tributar'],
  ['tri-r05','tributario','Depósito integral','Em ação judicial tributária, o contribuinte realiza depósito integral do montante discutido, nos termos da legislação aplicável.','O depósito do montante integral é causa de suspensão da exigibilidade do crédito tributário.','O depósito integral extingue automaticamente a obrigação tributária no momento em que é feito.','O depósito integral converte o tributo em isenção.','O depósito não produz qualquer efeito sobre a exigibilidade do crédito.','O CTN inclui o depósito do montante integral entre as hipóteses de suspensão da exigibilidade.','CTN, art. 151, II'],
  ['tri-r06','tributario','Parcelamento','Contribuinte adere a parcelamento tributário regularmente instituído e cumpre as condições do acordo.','O parcelamento suspende a exigibilidade do crédito tributário enquanto observado o regime aplicável.','O parcelamento extingue a competência tributária do ente.','O parcelamento é modalidade de imunidade.','A adesão ao parcelamento nunca interfere na exigibilidade do crédito.','O parcelamento está expressamente previsto no CTN entre as causas de suspensão da exigibilidade.','CTN, art. 151, VI'],
  ['tri-r07','tributario','Prescrição','Crédito tributário foi definitivamente constituído e, após isso, discute-se o prazo para a Fazenda exercer a pretensão de cobrança judicial.','A prescrição tributária relaciona-se ao prazo para cobrança do crédito já definitivamente constituído.','A prescrição ocorre sempre antes de qualquer constituição do crédito.','Prescrição e decadência são tecnicamente o mesmo instituto no CTN.','A prescrição impede o nascimento da competência tributária.','No CTN, decadência e prescrição atingem momentos distintos: constituição do crédito e pretensão de cobrança.','CTN, arts. 173 e 174'],
  ['tri-r08','tributario','Decadência','A Administração deixa transcorrer, sem efetuar validamente o lançamento, o prazo decadencial aplicável à constituição do crédito tributário.','A decadência pode extinguir o direito de constituir o crédito tributário quando esgotado o prazo legal.','A decadência somente começa após o ajuizamento da execução fiscal.','Decadência é prazo destinado exclusivamente ao contribuinte para pedir restituição.','A decadência suspende a exigibilidade de crédito já definitivamente constituído, sem extingui-lo.','A decadência tributária diz respeito ao prazo de constituição do crédito, conforme regras do CTN.','CTN, art. 173 e regras específicas'],
  ['tri-r09','tributario','Responsabilidade de terceiros','A Fazenda pretende cobrar tributo de terceiro que não realizou diretamente o fato gerador, invocando responsabilidade tributária.','A responsabilização de terceiros depende das hipóteses e requisitos previstos em lei; não decorre automaticamente do simples inadimplemento do contribuinte.','Todo administrador responde pessoalmente por qualquer tributo não pago, sem requisito adicional.','A responsabilidade de terceiro independe de previsão legal.','Qualquer empregado da empresa pode ser cobrado integralmente só porque trabalha no estabelecimento.','Responsabilidade tributária é matéria legalmente tipificada e exige enquadramento nos pressupostos normativos.','CTN, arts. 128 e seguintes'],
  ['tri-r10','tributario','Obrigação acessória','Empresa descumpre obrigação tributária acessória instituída pela legislação, embora não haja naquele momento tributo principal a pagar.','O descumprimento da obrigação acessória pode converter-se em obrigação principal relativamente à penalidade pecuniária.','Obrigação acessória jamais produz consequência pecuniária.','Toda obrigação acessória depende da existência prévia de imposto a recolher no mesmo período.','Obrigação acessória só pode ser criada por contrato entre Fisco e contribuinte.','O CTN disciplina deveres instrumentais e prevê consequência pecuniária pelo seu descumprimento.','CTN, art. 113'],

  // ADMINISTRATIVO
  ['adm-r01','administrativo','Atos administrativos','A Administração identifica ilegalidade em ato administrativo por ela praticado e discute se deve mantê-lo por conveniência.','A ilegalidade é fundamento para anulação do ato; revogação se relaciona a conveniência e oportunidade de ato válido, dentro dos limites jurídicos.','A Administração deve revogar todo ato ilegal e jamais anulá-lo.','Anulação só pode ocorrer por conveniência política.','Revogação e anulação são sinônimos perfeitos e produzem sempre os mesmos pressupostos.','O direito administrativo distingue invalidação por ilegalidade de retirada discricionária por mérito.','Princípios administrativos e disciplina legal dos atos'],
  ['adm-r02','administrativo','Responsabilidade civil do Estado','Agente público, atuando nessa qualidade, causa dano a particular, que busca indenização do ente estatal.','Em regra, a responsabilidade do Estado perante a vítima é objetiva, preservado direito de regresso contra o agente nos casos de dolo ou culpa.','A vítima sempre precisa provar culpa pessoal do agente para responsabilizar o Estado.','O direito de regresso contra o agente independe de dolo ou culpa.','O Estado nunca responde por atos de seus agentes.','A Constituição adota responsabilidade objetiva estatal perante o lesado e regresso subjetivo contra o agente.','Constituição Federal, art. 37, §6º'],
  ['adm-r03','administrativo','Licitações','Órgão público estrutura licitação e pretende direcionar o certame sem justificativa, afastando a competição e a isonomia entre potenciais licitantes.','A licitação deve observar isonomia, competição e busca de resultado vantajoso, entre outros princípios e objetivos legais.','A licitação tem por finalidade impedir competição para facilitar a escolha administrativa.','A Administração pode direcionar livremente o objeto a fornecedor específico sem fundamento legal.','Isonomia entre licitantes não integra o regime jurídico das contratações públicas.','A Lei 14.133/2021 estrutura o processo licitatório em torno de competição, isonomia, planejamento e contratação vantajosa.','Lei 14.133/2021, objetivos e princípios da licitação'],
  ['adm-r04','administrativo','Contratação direta','Autoridade pretende contratar diretamente fornecedor sem licitação e sem demonstrar hipótese legal ou motivação do procedimento.','A contratação direta é excepcional e exige enquadramento em hipótese legal e instrução/motivação adequada do processo.','A contratação direta é a regra geral e dispensa qualquer justificativa.','A Administração pode afastar a licitação apenas por preferência pessoal do gestor.','Toda contratação direta é necessariamente ilícita, mesmo quando a lei prevê dispensa ou inexigibilidade.','Dispensa e inexigibilidade são hipóteses legais de contratação direta, sujeitas a requisitos e procedimento próprio.','Lei 14.133/2021, contratação direta'],
  ['adm-r05','administrativo','Concurso público','Órgão pretende preencher cargo efetivo permanente mediante simples indicação política, sem concurso, inexistindo exceção constitucional.','A investidura em cargo ou emprego público depende, em regra, de aprovação prévia em concurso público, ressalvadas as hipóteses constitucionais.','Todo cargo efetivo pode ser preenchido livremente por nomeação política.','Concurso público é exigido somente para cargos em comissão.','A Constituição proíbe concurso para empregos públicos.','A regra constitucional é o concurso para cargos e empregos, com exceção dos cargos em comissão definidos em lei.','Constituição Federal, art. 37, II'],
  ['adm-r06','administrativo','Serviço público','Poder Público pretende delegar prestação de serviço público por concessão a particular.','A concessão de serviço público depende de licitação, observada a legislação aplicável.','A concessão pode ser entregue definitivamente a qualquer particular sem procedimento competitivo.','Serviço público nunca pode ser delegado a particular.','A concessão dispensa contrato e qualquer controle estatal.','A Constituição admite prestação indireta por concessão ou permissão, sempre através de licitação nos termos legais.','Constituição Federal, art. 175'],
  ['adm-r07','administrativo','Improbidade administrativa','Agente público pratica conduta apenas culposa e a acusação pretende enquadrá-la automaticamente como ato de improbidade após as alterações legislativas que passaram a exigir dolo para a tipificação.','A configuração dos atos de improbidade sujeitos à Lei 8.429/1992 exige o elemento subjetivo previsto na legislação vigente, não bastando transformar qualquer culpa em improbidade.','Qualquer erro administrativo culposo constitui necessariamente improbidade.','Improbidade é responsabilidade objetiva e independe de elemento subjetivo.','A mera ilegalidade formal sempre gera, automaticamente, condenação por improbidade.','A Lei de Improbidade, após reforma legislativa, reforçou a exigência de dolo para os atos tipificados.','Lei 8.429/1992 com alterações da Lei 14.230/2021'],
  ['adm-r08','administrativo','Motivação','Autoridade administrativa decide questão que restringe direito do administrado e apresenta apenas fórmula genérica, sem indicar fatos ou fundamentos jurídicos relevantes.','A motivação deve explicitar os fundamentos fáticos e jurídicos quando exigida pelo ordenamento, permitindo controle da decisão.','A Administração nunca precisa motivar decisões que afetem direitos.','Basta indicar a preferência pessoal da autoridade como fundamento suficiente.','Motivação só existe em decisões judiciais, não administrativas.','A motivação integra o devido processo administrativo e permite verificar legalidade, finalidade e racionalidade da decisão.','Lei 9.784/1999, motivação dos atos administrativos'],
  ['adm-r09','administrativo','Desapropriação','O Estado desapropria bem particular por necessidade ou utilidade pública em hipótese submetida à regra geral constitucional de indenização.','A regra geral exige justa e prévia indenização em dinheiro, ressalvadas as exceções constitucionais específicas.','Toda desapropriação é gratuita.','A indenização só pode ocorrer décadas depois da perda do bem.','A Constituição proíbe qualquer desapropriação por utilidade pública.','A Constituição condiciona a desapropriação ordinária à indenização justa e prévia em dinheiro, sem prejuízo de regimes especiais.','Constituição Federal, art. 5º, XXIV'],
  ['adm-r10','administrativo','Revogação','A Administração reavalia ato discricionário válido e entende que ele deixou de ser conveniente ao interesse público, sem haver ilegalidade.','Pode haver revogação por razões de mérito administrativo, respeitados os limites jurídicos e situações protegidas.','O único meio de retirar ato válido é anulá-lo por ilegalidade inexistente.','Revogação é sanção penal aplicada ao agente que praticou o ato.','A Administração é obrigada a manter para sempre todo ato discricionário válido.','Revogação é retirada de ato válido por conveniência e oportunidade, ao contrário da anulação por vício de legalidade.','Regime jurídico dos atos administrativos'],

  // CIVIL
  ['civ-r01','civil','Responsabilidade civil','Pessoa causa dano a outra mediante conduta culposa, havendo nexo causal comprovado e inexistindo regime especial de responsabilidade objetiva.','Na responsabilidade subjetiva, a reparação pressupõe conduta, dano, nexo causal e culpa ou dolo conforme o caso.','Basta existir dano, sem qualquer nexo com a conduta do agente.','Responsabilidade civil subjetiva exige condenação penal prévia.','A culpa é juridicamente irrelevante em toda e qualquer responsabilidade civil.','O Código Civil adota como regra geral responsabilidade baseada em ato ilícito, dano e nexo, com elemento subjetivo quando exigido.','Código Civil, arts. 186 e 927'],
  ['civ-r02','civil','Responsabilidade objetiva','Atividade normalmente desenvolvida pelo autor do dano implica, por sua natureza, risco para direitos de terceiros, nas condições previstas em lei.','Pode haver obrigação de reparar independentemente de culpa nas hipóteses legais e nas atividades de risco contempladas pelo Código Civil.','Responsabilidade objetiva é proibida no direito civil brasileiro.','Mesmo em hipótese legal objetiva, a vítima deve sempre provar dolo específico.','Toda responsabilidade civil é automática e dispensa dano e nexo causal.','O Código Civil admite responsabilidade sem culpa em hipóteses previstas em lei ou vinculadas ao risco da atividade.','Código Civil, art. 927, parágrafo único'],
  ['civ-r03','civil','Prescrição','Após violação de direito subjetivo nasce pretensão exigível, e o titular permanece inerte durante o prazo prescricional aplicável.','A prescrição atinge a pretensão decorrente da violação do direito, conforme o regime e os prazos legais.','Prescrição extingue a personalidade civil do titular.','Prescrição é sinônimo de nulidade absoluta do negócio jurídico.','A prescrição impede a existência de qualquer direito material desde o nascimento.','O Código Civil vincula a prescrição à pretensão nascida com a violação do direito.','Código Civil, art. 189'],
  ['civ-r04','civil','Boa-fé objetiva','Partes executam contrato de longa duração e uma delas adota conduta contraditória capaz de frustrar confiança legitimamente criada na outra.','A boa-fé objetiva impõe padrões de lealdade, cooperação e proteção da confiança durante a relação contratual.','A boa-fé objetiva elimina toda autonomia privada e torna irrelevante o contrato.','Boa-fé objetiva só se aplica depois do inadimplemento definitivo.','As partes podem agir contraditoriamente sem qualquer limite se o contrato não mencionar boa-fé.','A boa-fé objetiva funciona como padrão de conduta e fonte de deveres anexos na relação obrigacional.','Código Civil, arts. 113 e 422'],
  ['civ-r05','civil','Abuso de direito','Titular exerce posição jurídica de modo manifestamente excessivo, contrariando seu fim econômico ou social, a boa-fé ou os bons costumes.','O exercício abusivo pode configurar ato ilícito, ainda que formalmente se invoque um direito.','Quem possui um direito nunca pode praticar ato ilícito ao exercê-lo.','Abuso de direito só existe se houver crime tipificado.','A boa-fé é irrelevante para avaliar exercício abusivo de direito.','O Código Civil considera ilícito o exercício de direito que excede manifestamente os limites juridicamente impostos.','Código Civil, art. 187'],
  ['civ-r06','civil','Enriquecimento sem causa','Pessoa obtém vantagem patrimonial injustificada às custas de outra, sem causa jurídica que autorize a retenção.','Quem se enriquece sem justa causa às custas de outrem deve restituir o indevidamente auferido, na medida do enriquecimento.','O enriquecimento sem causa é sempre permitido se não houver contrato escrito.','A restituição exige necessariamente prática de crime.','A vantagem sem causa nunca gera obrigação civil de restituição.','O Código Civil veda enriquecimento injustificado e disciplina dever de restituição.','Código Civil, art. 884'],
  ['civ-r07','civil','Solidariedade','Dois devedores assumem obrigação comum, mas nem a lei nem o contrato estabelecem solidariedade entre eles.','A solidariedade não se presume; resulta da lei ou da vontade das partes.','Toda pluralidade de devedores gera solidariedade automática.','Solidariedade só pode surgir por decisão judicial depois do inadimplemento.','A lei proíbe solidariedade convencional.','O Código Civil exige fonte legal ou negocial para solidariedade.','Código Civil, art. 265'],
  ['civ-r08','civil','Novação','Credor e devedor substituem obrigação anterior por nova, discutindo-se se houve intenção inequívoca de novar.','A novação pressupõe obrigação nova e intenção de novar; na ausência de ânimo inequívoco, a nova obrigação pode apenas confirmar a anterior.','Toda alteração de prazo implica novação automática.','Novação ocorre sem qualquer manifestação de vontade.','A existência de obrigação anterior impede juridicamente novação.','A novação exige elementos próprios, incluindo animus novandi expresso ou inequivocamente demonstrado.','Código Civil, arts. 360 e 361'],
  ['civ-r09','civil','Posse e propriedade','Pessoa exerce de fato poderes inerentes à propriedade sobre determinado bem, embora não apresente título de domínio.','A posse é situação juridicamente protegida e pode existir independentemente da comprovação imediata da propriedade.','Somente o proprietário registrado pode ser possuidor.','Posse e propriedade são conceitos idênticos em todas as situações.','Quem não tem domínio jamais recebe proteção possessória.','O Código Civil distingue posse de propriedade e tutela o exercício fático de poderes sobre a coisa.','Código Civil, arts. 1.196 e seguintes'],
  ['civ-r10','civil','Função social do contrato','Contrato é interpretado e executado em contexto no qual uma parte sustenta que a liberdade contratual é absoluta e imune a qualquer limite social.','A liberdade contratual é exercida nos limites da função social do contrato e em conformidade com a boa-fé.','A função social elimina a liberdade contratual e torna nulos todos os contratos privados.','Contratos privados são imunes a princípios legais de ordem pública.','A função social só existe em contratos administrativos.','O Código Civil compatibiliza autonomia privada com função social e boa-fé.','Código Civil, arts. 421 e 422'],

  // PROCESSO CIVIL
  ['pcv-r01','processo-civil','Recursos','Juiz profere sentença em procedimento comum e a parte vencida pretende impugnar a decisão pela via recursal ordinária adequada.','Em regra, cabe apelação contra sentença.','Cabe agravo interno diretamente contra qualquer sentença de primeiro grau.','Sentença só pode ser impugnada por mandado de segurança.','Despacho de mero expediente é o recurso próprio contra sentença.','O CPC estabelece a apelação como recurso ordinário contra sentença.','CPC, art. 1.009'],
  ['pcv-r02','processo-civil','Competência','Réu entende que o juízo é relativamente incompetente e vai apresentar sua primeira defesa no procedimento comum.','A incompetência relativa deve ser arguida, em regra, como preliminar de contestação.','A incompetência relativa só pode ser arguida após o trânsito em julgado.','A alegação exige sempre ação autônoma separada.','A incompetência relativa pode ser ignorada e reconhecida de ofício em qualquer tempo sem disciplina processual.','O CPC concentrou a alegação de incompetência absoluta e relativa em preliminar de contestação, com regimes próprios.','CPC, art. 64'],
  ['pcv-r03','processo-civil','Tutela de urgência','Autor pede tutela provisória urgente e apresenta elementos que demonstram probabilidade do direito e risco de dano antes do julgamento final.','A tutela de urgência exige probabilidade do direito e perigo de dano ou risco ao resultado útil do processo.','Tutela de urgência exige trânsito em julgado prévio.','A medida depende de confissão da parte contrária.','Urgência é irrelevante e nunca autoriza tutela antes da sentença.','O CPC estrutura a tutela de urgência sobre probabilidade do direito e perigo de dano ou risco ao resultado útil.','CPC, art. 300'],
  ['pcv-r04','processo-civil','Ônus da prova','Em ação indenizatória comum, discute-se a distribuição ordinária do ônus da prova entre autor e réu.','Em regra, cabe ao autor provar fato constitutivo de seu direito e ao réu provar fato impeditivo, modificativo ou extintivo.','Todo o ônus da prova pertence sempre ao réu.','O autor nunca precisa provar fatos que fundamentam sua pretensão.','O juiz é o único responsável por produzir todas as provas das partes.','O CPC prevê distribuição estática do ônus, sem prejuízo das hipóteses de distribuição dinâmica.','CPC, art. 373'],
  ['pcv-r05','processo-civil','Revelia','Réu não apresenta contestação e o autor sustenta que o juiz está obrigado a acolher integralmente qualquer alegação feita na inicial.','A revelia pode produzir presunção de veracidade de fatos, mas possui exceções e não implica procedência automática do pedido.','A revelia sempre obriga o juiz a julgar procedente todo pedido, mesmo juridicamente impossível.','A revelia extingue o processo sem resolução do mérito.','Réu revel é considerado autor da ação.','Os efeitos da revelia são juridicamente delimitados e não substituem a análise do direito aplicável nem das exceções legais.','CPC, arts. 344 e 345'],
  ['pcv-r06','processo-civil','Prazos','Advogado calcula prazo processual fixado em dias pelo CPC e considera se sábados, domingos e feriados entram na contagem.','Na contagem de prazo processual em dias computam-se somente os dias úteis, salvo disciplina específica diversa.','Todo prazo processual em dias é contado de forma corrida, incluindo todos os fins de semana.','Dias úteis só são considerados em processos penais.','A regra de dias úteis vale apenas para prazos do juiz, nunca das partes.','O CPC estabelece contagem em dias úteis para prazos processuais expressos em dias.','CPC, art. 219'],
  ['pcv-r07','processo-civil','Honorários sucumbenciais','Sentença condena a parte vencida e surge discussão sobre a fixação de honorários do advogado da parte vencedora.','O CPC prevê condenação do vencido ao pagamento de honorários ao advogado do vencedor, observados critérios e hipóteses legais.','Honorários sucumbenciais são proibidos no processo civil.','Somente a parte, nunca seu advogado, pode ser titular de honorários sucumbenciais.','O juiz só pode fixar honorários se as partes tiverem previsto isso no contrato entre si.','A sucumbência integra o regime processual de despesas e honorários, com disciplina própria no CPC.','CPC, art. 85'],
  ['pcv-r08','processo-civil','Execução menos gravosa','Executado invoca o princípio da menor onerosidade para rejeitar meio executivo e não indica alternativa eficaz que satisfaça o credor.','A menor onerosidade não elimina a efetividade da execução; ao alegar meio mais gravoso, o executado deve indicar alternativa menos onerosa e eficaz quando a lei assim exige.','O devedor pode impedir qualquer execução apenas afirmando que ela é incômoda.','O princípio autoriza deixar o credor sem satisfação indefinidamente.','A escolha do meio executivo pertence sempre exclusivamente ao devedor.','O CPC busca equilibrar efetividade para o credor e menor onerosidade possível ao executado.','CPC, art. 805'],
  ['pcv-r09','processo-civil','Coisa julgada','Decisão de mérito transitada em julgado torna-se imutável e indiscutível nos limites definidos pelo ordenamento, salvo instrumentos excepcionais previstos em lei.','A coisa julgada material estabiliza a decisão de mérito nos limites legais e não pode ser simplesmente ignorada por nova ação idêntica.','Trânsito em julgado não produz qualquer estabilidade jurídica.','Toda decisão transitada em julgado pode ser revogada livremente pelo mesmo juiz a qualquer tempo.','Coisa julgada existe apenas em processos criminais.','O CPC disciplina a autoridade da coisa julgada e instrumentos excepcionais para sua desconstituição.','CPC, arts. 502 e seguintes'],
  ['pcv-r10','processo-civil','Contraditório','Juiz identifica fundamento jurídico relevante que nenhuma das partes discutiu e pretende decidir imediatamente com base nele, sem oportunidade de manifestação.','O CPC veda decisão-surpresa e exige que as partes tenham oportunidade de se manifestar sobre fundamento relevante, ainda que cognoscível de ofício.','O juiz pode sempre decidir com fundamento totalmente novo sem ouvir as partes.','Contraditório significa apenas permitir recurso depois da sentença.','A vedação à decisão-surpresa só existe quando ambas as partes são pessoas físicas.','O contraditório contemporâneo inclui direito de influência e proibição de decisão fundada em questão sobre a qual não houve oportunidade de manifestação.','CPC, arts. 9º e 10'],

  // PENAL
  ['pen-r01','penal','Tentativa','Agente inicia atos de execução de crime, mas a consumação não ocorre por circunstâncias alheias à sua vontade.','Há tentativa punível, salvo hipóteses legais específicas, porque houve início de execução e não consumação por circunstâncias alheias à vontade do agente.','Há apenas cogitação impunível porque o crime não se consumou.','Todo crime tentado recebe necessariamente a mesma pena do consumado sem redução.','Tentativa exige que o agente desista voluntariamente antes de iniciar a execução.','O Código Penal define tentativa pelo início de execução e não consumação por circunstâncias alheias à vontade.','Código Penal, art. 14, II'],
  ['pen-r02','penal','Desistência voluntária','Após iniciar a execução, o agente voluntariamente decide interromper os atos que ainda poderia continuar e evita a consumação.','Na desistência voluntária, o agente responde pelos atos já praticados, e não pela tentativa do crime inicialmente pretendido.','A desistência voluntária nunca produz efeito jurídico.','O agente responde sempre pelo crime consumado, ainda que a consumação não ocorra.','A desistência voluntária depende de intervenção externa que impeça a continuação.','O Código Penal trata desistência voluntária e arrependimento eficaz como formas de afastar a tentativa, mantendo responsabilidade pelos atos já praticados.','Código Penal, art. 15'],
  ['pen-r03','penal','Crime impossível','Agente tenta praticar crime utilizando meio absolutamente ineficaz, de modo que a consumação é objetivamente impossível nas circunstâncias.','Não se pune a tentativa quando, por absoluta ineficácia do meio ou absoluta impropriedade do objeto, é impossível consumar o crime.','Crime impossível recebe sempre pena superior ao crime consumado.','A absoluta ineficácia do meio é juridicamente irrelevante.','Todo erro de execução configura crime impossível.','O Código Penal exclui a punição da tentativa no crime impossível em hipóteses de impossibilidade absoluta.','Código Penal, art. 17'],
  ['pen-r04','penal','Erro de tipo','Agente incorre em erro sobre elemento constitutivo do tipo legal de crime, afastando a consciência sobre esse elemento.','O erro sobre elemento constitutivo do tipo pode excluir o dolo, permitindo punição por culpa se houver previsão legal e se presentes seus requisitos.','Erro de tipo jamais interfere no dolo.','Erro de tipo transforma automaticamente todo fato em crime doloso mais grave.','A culpa é sempre punível mesmo quando não existe modalidade culposa prevista.','O Código Penal disciplina o erro de tipo como causa capaz de excluir dolo e ressalva a punição culposa quando prevista.','Código Penal, art. 20'],
  ['pen-r05','penal','Erro de proibição','Agente, em situação juridicamente justificável, não possui possibilidade de compreender a ilicitude do fato, caracterizando erro inevitável sobre a proibição.','O erro inevitável sobre a ilicitude pode isentar de pena; se evitável, pode autorizar redução nos termos da lei.','Erro de proibição nunca produz efeito sobre a culpabilidade.','Todo desconhecimento alegado da lei gera absolvição automática.','Erro de proibição exclui sempre a tipicidade do fato.','O Código Penal diferencia erro de proibição inevitável e evitável para fins de culpabilidade e pena.','Código Penal, art. 21'],
  ['pen-r06','penal','Concurso de pessoas','Em crime praticado por várias pessoas, discute-se se condição pessoal de um dos agentes se comunica aos demais.','Circunstâncias e condições de caráter pessoal não se comunicam, salvo quando elementares do crime.','Toda condição pessoal de um agente se comunica automaticamente a todos.','Nenhuma elementar do crime pode se comunicar entre os participantes.','A regra de comunicabilidade depende apenas da vontade do juiz.','O Código Penal distingue circunstâncias pessoais de elementares do delito no concurso de pessoas.','Código Penal, art. 30'],
  ['pen-r07','penal','Legítima defesa','Pessoa repele agressão injusta, atual ou iminente, usando moderadamente os meios necessários para proteger direito próprio ou de terceiro.','A situação pode configurar legítima defesa se presentes os requisitos legais.','Legítima defesa exige agressão passada e já encerrada há longo tempo.','Qualquer excesso é automaticamente protegido pela legítima defesa.','Só existe legítima defesa para proteger patrimônio próprio, nunca terceiro.','O Código Penal exige agressão injusta atual ou iminente e uso moderado dos meios necessários.','Código Penal, art. 25'],
  ['pen-r08','penal','Estado de necessidade','Pessoa pratica fato para salvar de perigo atual, que não provocou voluntariamente e não podia evitar de outro modo, direito próprio ou alheio, nas condições legais.','A situação pode configurar estado de necessidade quando preenchidos os requisitos do Código Penal.','Estado de necessidade exige que o agente tenha criado voluntariamente o perigo para poder invocá-lo.','O instituto só existe em crimes contra o patrimônio.','Não importa se era razoável exigir o sacrifício do direito ameaçado.','O Código Penal condiciona o estado de necessidade a perigo atual e a requisitos específicos de inevitabilidade e proporcionalidade jurídica.','Código Penal, art. 24'],
  ['pen-r09','penal','Omissão imprópria','Pessoa que tinha dever jurídico e possibilidade de agir para evitar resultado típico permanece inerte, nas hipóteses em que a lei a coloca na posição de garantidor.','A omissão pode ser penalmente relevante quando o omitente devia e podia agir para evitar o resultado, nos casos definidos em lei.','Nenhuma omissão pode gerar responsabilidade por resultado.','Qualquer pessoa responde por todo resultado que não conseguiu impedir, mesmo sem dever de agir.','A posição de garantidor depende apenas de vínculo de amizade.','O Código Penal define hipóteses em que a omissão é relevante por existir dever jurídico de impedir o resultado.','Código Penal, art. 13, §2º'],
  ['pen-r10','penal','Extinção da punibilidade','Após o decurso do prazo prescricional penal aplicável, reconhece-se a prescrição nos termos da lei.','A prescrição é causa de extinção da punibilidade.','A prescrição é circunstância agravante da pena.','Prescrição integra o tipo penal como elemento objetivo.','Prescrição só produz efeitos civis e nunca penais.','O Código Penal inclui a prescrição entre as causas de extinção da punibilidade.','Código Penal, art. 107'],

  // PROCESSO PENAL
  ['ppn-r01','processo-penal','Ação penal','Crime é de ação penal pública incondicionada e estão presentes os pressupostos para persecução em juízo.','A titularidade da ação penal pública é, em regra, do Ministério Público.','A ação penal pública é proposta exclusivamente pelo delegado de polícia.','O juiz é titular da ação penal pública e oferece a denúncia.','A vítima é sempre a única titular da ação penal pública incondicionada.','A Constituição atribui ao Ministério Público a promoção privativa da ação penal pública, ressalvadas hipóteses constitucionais.','Constituição Federal, art. 129, I, e CPP'],
  ['ppn-r02','processo-penal','Provas ilícitas','Acusação pretende utilizar prova obtida por meio ilícito como fundamento ordinário da condenação.','Provas obtidas por meios ilícitos são inadmissíveis, observada a disciplina constitucional e legal sobre provas derivadas e exceções.','A origem ilícita da prova é irrelevante no processo penal.','Toda prova ilícita torna-se válida se favorecer a acusação.','A Constituição autoriza prova ilícita sempre que o crime imputado for grave.','A inadmissibilidade da prova ilícita é garantia constitucional, complementada pelo CPP.','Constituição Federal, art. 5º, LVI, e CPP'],
  ['ppn-r03','processo-penal','Prisão preventiva','Após denúncia, o juiz cogita decretar prisão preventiva automaticamente apenas porque a imputação é grave, sem demonstrar os requisitos cautelares do caso.','A prisão preventiva é medida cautelar excepcional e exige fundamentação concreta e pressupostos legais; não decorre automaticamente da denúncia.','Toda denúncia gera prisão preventiva obrigatória.','Prisão preventiva é pena definitiva antecipada.','A preventiva pode ser decretada sem qualquer fundamentação.','O CPP submete a prisão preventiva a requisitos, fundamentos cautelares e motivação individualizada.','CPP, arts. 312 e 315'],
  ['ppn-r04','processo-penal','Elementos do inquérito','Sentença condenatória é fundamentada exclusivamente em informações colhidas no inquérito, sem enquadramento em prova cautelar, não repetível ou antecipada.','O juiz não pode fundamentar a decisão exclusivamente em elementos informativos da investigação, ressalvadas as provas cautelares, não repetíveis e antecipadas.','O inquérito substitui integralmente a prova judicial contraditória em qualquer caso.','Elementos do inquérito nunca podem ser considerados nem mesmo junto com provas judiciais.','Toda informação policial possui automaticamente valor de prova judicial plena.','O CPP limita o uso exclusivo de elementos informativos e ressalva categorias probatórias específicas.','CPP, art. 155'],
  ['ppn-r05','processo-penal','Confissão','Réu confessa durante o processo e depois se retrata, havendo outras provas a serem avaliadas pelo juiz.','A confissão é divisível e retratável e deve ser apreciada em conjunto com as demais provas.','A confissão é irrevogável e vincula o juiz de modo absoluto.','A confissão dispensa sempre qualquer exame do restante da prova.','Retratação torna automaticamente inválido todo o processo.','O CPP afasta valor absoluto da confissão e determina sua apreciação no conjunto probatório.','CPP, arts. 197 a 200'],
  ['ppn-r06','processo-penal','Habeas corpus','Pessoa sofre ou se acha ameaçada de sofrer coação ilegal em sua liberdade de locomoção.','O habeas corpus é remédio adequado para proteger a liberdade de locomoção contra ilegalidade ou abuso de poder.','Habeas corpus é ação destinada exclusivamente a revisar contratos civis.','O remédio só pode ser impetrado depois do trânsito em julgado.','Habeas corpus serve apenas para corrigir bancos de dados pessoais.','A Constituição e o CPP associam o habeas corpus à proteção da liberdade de ir, vir e permanecer.','Constituição Federal, art. 5º, LXVIII, e CPP'],
  ['ppn-r07','processo-penal','Tribunal do Júri','Acusação envolve crime doloso contra a vida sujeito à competência constitucional do Tribunal do Júri.','A Constituição reconhece a competência do Tribunal do Júri para o julgamento dos crimes dolosos contra a vida, observada a legislação processual.','Todo crime patrimonial é obrigatoriamente julgado pelo Tribunal do Júri.','O Júri só julga infrações administrativas.','A competência constitucional do Júri pode ser eliminada por simples ato administrativo.','A competência mínima constitucional do Júri abrange os crimes dolosos contra a vida.','Constituição Federal, art. 5º, XXXVIII'],
  ['ppn-r08','processo-penal','Presunção de inocência','Acusação pretende impor ao réu o dever de provar sua inocência como regra geral para evitar condenação criminal.','A presunção de inocência e a estrutura acusatória impedem transformar o acusado em responsável geral por provar sua não culpabilidade.','O réu é juridicamente considerado culpado desde a abertura do inquérito.','A acusação não precisa demonstrar os fatos constitutivos da imputação.','A dúvida relevante sobre a autoria sempre deve ser resolvida contra o acusado.','A Constituição assegura estado de não culpabilidade até o trânsito em julgado, repercutindo na distribuição do ônus argumentativo e probatório da acusação.','Constituição Federal, art. 5º, LVII'],
  ['ppn-r09','processo-penal','Cadeia de custódia','Vestígio coletado em investigação passa por procedimentos de reconhecimento, isolamento, coleta, acondicionamento e rastreamento.','A cadeia de custódia busca manter e documentar a história cronológica do vestígio desde seu reconhecimento até o descarte.','Cadeia de custódia é irrelevante para prova material.','A cadeia de custódia começa apenas depois da sentença.','O CPP proíbe qualquer registro de quem manipulou o vestígio.','O CPP disciplina cadeia de custódia para preservação da integridade e rastreabilidade do vestígio.','CPP, arts. 158-A e seguintes'],
  ['ppn-r10','processo-penal','Contraditório e defesa','Acusado é privado de conhecer a acusação e de exercer defesa técnica e autodefesa nos momentos processuais previstos em lei.','O processo penal deve observar contraditório e ampla defesa, com os meios e recursos a ela inerentes.','Ampla defesa é dispensável sempre que a acusação considerar a prova forte.','Contraditório só existe em processos civis.','A Constituição permite condenação sem conhecimento prévio da acusação.','Contraditório e ampla defesa são garantias constitucionais aplicáveis aos processos judiciais e administrativos.','Constituição Federal, art. 5º, LV'],

  // TRABALHO
  ['tra-r01','trabalho','Relação de emprego','Pessoa física presta serviços de forma pessoal, onerosa, não eventual e subordinada a empregador.','Os elementos descritos são compatíveis com relação de emprego, observados os demais dados concretos.','Relação de emprego exige necessariamente prestação gratuita e eventual.','Subordinação é incompatível com vínculo de emprego.','Pessoalidade e onerosidade afastam o vínculo empregatício.','A CLT estrutura a relação de emprego em torno de prestação pessoal, não eventual, onerosa e subordinada.','CLT, arts. 2º e 3º'],
  ['tra-r02','trabalho','Jornada','Empregado urbano comum, sem regime especial, trabalha acima de oito horas diárias e quarenta e quatro semanais sem hipótese válida de compensação.','A Constituição fixa, como regra geral, jornada normal não superior a oito horas diárias e quarenta e quatro semanais, admitindo compensação e regimes legais.','A Constituição estabelece jornada comum de doze horas diárias e oitenta semanais.','Não existe limite constitucional de jornada.','A jornada máxima geral é de quatro horas por semana.','A duração normal do trabalho possui limites constitucionais, sem prejuízo de regimes especiais e negociação nos limites legais.','Constituição Federal, art. 7º, XIII'],
  ['tra-r03','trabalho','Horas extras','Empregado realiza serviço extraordinário além da jornada normal, sem regime mais favorável aplicável.','A remuneração do serviço extraordinário deve ser superior, no mínimo, em cinquenta por cento à do normal.','Hora extra deve ser paga com valor inferior à hora normal.','A Constituição fixa adicional máximo de dez por cento.','Serviço extraordinário nunca gera acréscimo remuneratório.','A Constituição assegura adicional mínimo de cinquenta por cento para o serviço extraordinário.','Constituição Federal, art. 7º, XVI'],
  ['tra-r04','trabalho','Férias','Empregado adquire direito a férias anuais e discute a remuneração constitucional correspondente.','As férias anuais são remuneradas com, pelo menos, um terço a mais do que o salário normal.','Férias reduzem obrigatoriamente o salário em um terço.','O adicional constitucional de férias é de cinco por cento.','Férias anuais não possuem qualquer acréscimo constitucional.','A Constituição garante férias remuneradas com adicional mínimo de um terço.','Constituição Federal, art. 7º, XVII'],
  ['tra-r05','trabalho','Estabilidade gestante','Empregada tem gravidez confirmada durante vínculo abrangido pela proteção constitucional transitória.','A empregada gestante possui garantia provisória de emprego desde a confirmação da gravidez até cinco meses após o parto, nos termos constitucionais.','A estabilidade começa apenas no dia do parto.','A gravidez nunca produz garantia provisória de emprego.','A estabilidade termina automaticamente no primeiro mês de gestação.','O ADCT estabelece garantia de emprego da gestante no período constitucionalmente definido.','ADCT, art. 10, II, b'],
  ['tra-r06','trabalho','Irredutibilidade salarial','Empregador pretende reduzir unilateralmente o salário nominal de empregado sem autorização constitucional ou negocial válida.','O salário é irredutível, salvo o disposto em convenção ou acordo coletivo, dentro dos limites constitucionais e legais.','O empregador pode reduzir unilateralmente o salário a qualquer tempo.','A irredutibilidade salarial só protege servidores públicos.','A Constituição obriga redução anual do salário privado.','A Constituição protege a irredutibilidade salarial e admite negociação coletiva nas condições jurídicas cabíveis.','Constituição Federal, art. 7º, VI'],
  ['tra-r07','trabalho','Teletrabalho','Empregado presta serviços predominantemente fora das dependências do empregador, com uso de tecnologias de informação, mas continuam presentes pessoalidade, onerosidade e subordinação.','O trabalho remoto, por si só, não elimina a possibilidade de vínculo de emprego quando presentes os requisitos legais.','Teletrabalho é sempre atividade autônoma sem vínculo.','O uso de computador impede juridicamente a subordinação.','Qualquer serviço fora da sede extingue automaticamente o contrato de trabalho.','A CLT disciplina teletrabalho como modalidade de prestação laboral, sem afastar automaticamente a relação de emprego.','CLT, arts. 75-A e seguintes'],
  ['tra-r08','trabalho','Alteração contratual','Empregador altera unilateralmente condição contratual de modo prejudicial ao empregado, sem base legal ou consentimento válido.','Alterações contratuais lesivas encontram limite no princípio da inalterabilidade prejudicial previsto na CLT.','O empregador pode modificar qualquer condição contratual com prejuízo ao empregado por simples decisão.','Toda alteração contratual exige novo concurso público.','A proteção contra alteração lesiva existe apenas após a aposentadoria.','A CLT limita alterações contratuais que resultem direta ou indiretamente em prejuízo ao empregado.','CLT, art. 468'],
  ['tra-r09','trabalho','FGTS','Empregador deixa de efetuar depósitos de FGTS de empregado submetido ao regime geral do fundo.','O FGTS constitui direito social do trabalhador e os depósitos são obrigação do empregador nos termos da legislação específica.','FGTS é contribuição facultativa do empregado sem participação do empregador.','O empregador pode substituir o FGTS por promessa verbal de pagamento futuro.','FGTS só existe para servidores estatutários.','A Constituição reconhece o FGTS como direito social, regulamentado por legislação própria.','Constituição Federal, art. 7º, III, e Lei 8.036/1990'],
  ['tra-r10','trabalho','Aviso prévio','Contrato de emprego por prazo indeterminado é encerrado sem justa causa e surge discussão sobre aviso prévio.','O aviso prévio é direito constitucional e possui duração proporcional ao tempo de serviço, nos termos da lei.','Aviso prévio é proibido nos contratos por prazo indeterminado.','A duração do aviso é sempre de um único dia.','O aviso prévio só pode beneficiar o empregador, nunca o empregado.','A Constituição assegura aviso prévio proporcional, com mínimo de trinta dias, regulamentado por lei.','Constituição Federal, art. 7º, XXI'],

  // PROCESSO DO TRABALHO
  ['ptr-r01','processo-trabalho','Competência','Empregado ajuíza demanda decorrente diretamente de sua relação de trabalho contra o empregador.','A Justiça do Trabalho possui competência constitucional para processar e julgar ações oriundas da relação de trabalho, observadas as delimitações constitucionais e jurisprudenciais.','Toda demanda trabalhista é de competência exclusiva da Justiça Federal comum.','A Justiça do Trabalho só pode julgar crimes contra a organização do trabalho.','Relações de trabalho nunca integram a competência trabalhista.','A Constituição ampliou a competência material da Justiça do Trabalho para ações oriundas da relação de trabalho.','Constituição Federal, art. 114'],
  ['ptr-r02','processo-trabalho','Recurso ordinário','Vara do Trabalho profere sentença definitiva e a parte pretende utilizar o recurso ordinário cabível na sistemática da CLT.','O recurso ordinário é cabível nas hipóteses legais contra decisões definitivas ou terminativas das Varas e possui prazo trabalhista próprio.','Sentença de Vara do Trabalho só admite recurso extraordinário direto ao STF.','Recurso ordinário é exclusivo do processo penal.','Não existe recurso contra sentença trabalhista.','A CLT disciplina recurso ordinário como via ordinária de impugnação de decisões de primeiro grau trabalhista.','CLT, art. 895'],
  ['ptr-r03','processo-trabalho','Agravo de petição','Na fase de execução trabalhista, a parte pretende impugnar decisão do juiz nas hipóteses previstas na CLT.','O agravo de petição é recurso típico da execução trabalhista, observados seus requisitos legais.','Agravo de petição é o recurso ordinário contra toda sentença de conhecimento.','Na execução trabalhista nenhum recurso é admissível.','Agravo de petição é exclusivo do processo civil no STJ.','A CLT prevê agravo de petição para impugnações próprias da fase executiva.','CLT, art. 897, a'],
  ['ptr-r04','processo-trabalho','Ônus da prova','Em reclamação trabalhista discute-se a distribuição ordinária do ônus probatório entre reclamante e reclamado.','Em regra, o reclamante prova o fato constitutivo de seu direito e o reclamado os fatos impeditivos, modificativos ou extintivos, sem prejuízo da distribuição dinâmica prevista em lei.','Todo ônus da prova pertence sempre ao empregador.','O reclamante nunca precisa provar fato constitutivo.','Não existe regra de ônus da prova no processo do trabalho.','A CLT incorporou disciplina de distribuição do ônus alinhada ao modelo processual contemporâneo.','CLT, art. 818'],
  ['ptr-r05','processo-trabalho','Efeito dos recursos','Parte interpõe recurso trabalhista e presume que ele suspenderá automaticamente a eficácia da decisão em qualquer hipótese.','Os recursos trabalhistas têm, em regra, efeito meramente devolutivo, admitidas exceções e medidas específicas previstas no ordenamento.','Todo recurso trabalhista tem sempre efeito suspensivo automático.','Nenhum recurso trabalhista produz efeito devolutivo.','A interposição do recurso extingue o processo de imediato.','A CLT adota como regra efeito devolutivo dos recursos trabalhistas.','CLT, art. 899'],
  ['ptr-r06','processo-trabalho','Execução','Partes estão representadas por advogados e o juízo pretende iniciar execução trabalhista de ofício fora das hipóteses permitidas pela redação atual da CLT.','A execução é promovida pelas partes, sendo admitida execução de ofício nas hipóteses legais, inclusive quando as partes não estiverem representadas por advogado.','A execução trabalhista é sempre iniciada de ofício, sem qualquer exceção.','A execução nunca pode ocorrer de ofício em nenhuma circunstância.','A representação por advogado obriga o juiz a extinguir a execução.','A reforma trabalhista limitou a iniciativa ex officio, mantendo hipóteses específicas previstas no art. 878 da CLT.','CLT, art. 878'],
  ['ptr-r07','processo-trabalho','Audiência','Reclamante deixa de comparecer injustificadamente à audiência em que sua presença era exigida e não se enquadra em hipótese de afastamento das consequências legais.','A ausência do reclamante pode acarretar arquivamento da reclamação, observadas as regras e exceções da CLT.','A ausência do reclamante sempre gera revelia do reclamado.','A falta do autor produz automaticamente sentença de procedência.','Comparecimento das partes é irrelevante em qualquer audiência trabalhista.','A CLT disciplina efeitos específicos para ausência do reclamante e do reclamado à audiência.','CLT, art. 844'],
  ['ptr-r08','processo-trabalho','Jus postulandi','Empregado pretende atuar pessoalmente em demanda trabalhista e acredita que o jus postulandi alcança indistintamente qualquer tribunal e recurso possível.','O jus postulandi possui limites e não alcança indistintamente todas as instâncias e ações, conforme legislação e jurisprudência consolidada do TST.','Jus postulandi é proibido em qualquer órgão da Justiça do Trabalho.','Jus postulandi permite atuação leiga em qualquer tribunal superior sem limite.','O instituto existe apenas para o empregador e nunca para o empregado.','A CLT admite postulação pessoal em âmbito próprio, mas a jurisprudência delimita sua extensão, especialmente perante o TST e ações autônomas.','CLT, art. 791, e Súmula 425 do TST'],
  ['ptr-r09','processo-trabalho','Conciliação','Durante processo trabalhista, as partes apresentam proposta de acordo e pedem homologação judicial.','A conciliação é fortemente prestigiada no processo do trabalho e pode ocorrer em diferentes momentos, sujeita ao controle judicial de legalidade.','A conciliação é proibida depois do ajuizamento da reclamação.','O juiz é obrigado a homologar qualquer acordo, mesmo se ilícito.','Acordo trabalhista somente pode ser firmado antes do contrato de emprego.','A CLT incentiva solução conciliatória, sem afastar o controle judicial sobre validade e alcance do ajuste.','CLT, princípios e regras de conciliação'],
  ['ptr-r10','processo-trabalho','Custas','Processo trabalhista termina com condenação e surge discussão sobre custas processuais no procedimento ordinário.','As custas seguem disciplina própria da CLT, em regra calculadas sobre base definida legalmente e suportadas pela parte responsável conforme o resultado processual.','Processo do trabalho nunca possui custas.','Custas são sempre pagas antecipadamente pelo empregado antes de ajuizar ação.','O juiz pode fixar custas sem qualquer referência à lei.','A CLT possui regime específico de custas, inclusive percentuais, base de cálculo e momento de recolhimento.','CLT, arts. 789 e seguintes'],

  // EMPRESARIAL
  ['emp-r01','empresarial','Sociedade limitada','Sócios de sociedade limitada integralizam capital e discutem extensão ordinária de sua responsabilidade pelas obrigações sociais.','Na limitada, a responsabilidade de cada sócio é restrita ao valor de suas quotas, mas todos respondem solidariamente pela integralização do capital social.','Todo sócio responde ilimitadamente por qualquer dívida social apenas por integrar a limitada.','Nenhum sócio possui responsabilidade pela integralização do capital.','A sociedade limitada não possui personalidade jurídica.','O Código Civil limita a responsabilidade pelas quotas e prevê solidariedade dos sócios pela integralização do capital.','Código Civil, art. 1.052'],
  ['emp-r02','empresarial','Empresário','Profissional exerce atividade econômica organizada para produção ou circulação de bens ou serviços e discute enquadramento como empresário.','A atividade econômica profissional e organizada voltada à produção ou circulação de bens ou serviços integra o conceito legal de empresário, ressalvadas exceções previstas no Código Civil.','Empresário é apenas quem exerce cargo público.','Toda profissão intelectual é automaticamente atividade empresária, sem considerar organização ou elemento de empresa.','O conceito de empresário exige atividade gratuita e eventual.','O Código Civil define empresário pela exploração profissional de atividade econômica organizada.','Código Civil, art. 966'],
  ['emp-r03','empresarial','Profissão intelectual','Médico exerce pessoalmente profissão intelectual sem organização empresarial que transforme a atividade em elemento de empresa.','O exercício de profissão intelectual, por si só, não caracteriza empresário, salvo se constituir elemento de empresa.','Todo profissional intelectual é empresário independentemente da forma de organização.','Profissional intelectual nunca pode ser empresário em nenhuma circunstância.','A lei considera empresário apenas quem vende bens físicos.','O parágrafo único do art. 966 diferencia profissão intelectual e hipótese em que ela se integra a organização empresarial.','Código Civil, art. 966, parágrafo único'],
  ['emp-r04','empresarial','Empresário rural','Produtor rural exerce profissionalmente atividade econômica rural e avalia os efeitos da inscrição no Registro Público de Empresas Mercantis.','O empresário rural pode requerer inscrição e, depois de inscrito, fica equiparado, para todos os efeitos, ao empresário sujeito a registro.','O produtor rural é proibido de se registrar como empresário.','A inscrição rural é sempre automática e independe de opção.','Registro transforma o produtor em sociedade anônima obrigatoriamente.','O Código Civil atribui tratamento específico e facultativo ao registro do empresário rural.','Código Civil, art. 971'],
  ['emp-r05','empresarial','Estabelecimento empresarial','Empresário reúne bens corpóreos e incorpóreos organizados para o exercício da empresa.','O estabelecimento é o complexo de bens organizado para o exercício da empresa por empresário ou sociedade empresária.','Estabelecimento empresarial é sinônimo exclusivo do imóvel onde funciona a empresa.','O estabelecimento compreende apenas dinheiro em caixa.','Não existe tratamento unitário do complexo de bens empresariais.','O Código Civil conceitua estabelecimento como complexo organizado de bens destinado ao exercício da empresa.','Código Civil, art. 1.142'],
  ['emp-r06','empresarial','Recuperação judicial','Empresa economicamente viável enfrenta crise e pretende utilizar recuperação judicial para reorganizar suas obrigações.','A recuperação judicial busca viabilizar a superação da crise econômico-financeira, preservando empresa viável, empregos e interesses dos credores nos termos da lei.','A recuperação judicial tem como finalidade principal punir o devedor.','A recuperação extingue automaticamente todos os créditos sem plano ou procedimento.','A lei proíbe qualquer negociação coletiva entre devedor e credores.','O art. 47 da Lei 11.101/2005 consagra preservação da empresa e superação da crise como objetivos do instituto.','Lei 11.101/2005, art. 47'],
  ['emp-r07','empresarial','Créditos na recuperação','Empresa pede recuperação judicial e surge controvérsia sobre quais créditos se submetem ao regime recuperacional.','Em regra, submetem-se à recuperação os créditos existentes na data do pedido, ainda que não vencidos, ressalvadas as exceções legais.','Somente créditos constituídos depois do pedido se submetem à recuperação.','Nenhum crédito anterior ao pedido pode ser atingido pelo plano.','A recuperação alcança automaticamente qualquer crédito sem exceção legal possível.','A Lei 11.101/2005 utiliza a existência do crédito na data do pedido como critério geral, preservando exceções específicas.','Lei 11.101/2005, art. 49'],
  ['emp-r08','empresarial','Títulos de crédito','Obrigação consta de título de crédito e uma parte sustenta que o direito cartular pode ser exigido além dos limites literais constantes do título sem qualquer fundamento externo.','O princípio da literalidade vincula o direito cartular ao conteúdo expresso no título, sem prejuízo das regras específicas de cada espécie.','Literalidade significa que qualquer obrigação não escrita integra automaticamente o título.','Títulos de crédito não possuem autonomia jurídica.','O conteúdo escrito no título é irrelevante para delimitar o direito cartular.','O Código Civil e a teoria cambiária reconhecem literalidade como característica central dos títulos de crédito.','Código Civil, arts. 887 e seguintes'],
  ['emp-r09','empresarial','Nome da limitada','Sócios constituem sociedade limitada e escolhem nome empresarial sem qualquer indicação do tipo societário.','O nome empresarial da limitada deve conter a palavra limitada ou sua abreviatura, observada a disciplina do Código Civil.','Sociedade limitada é proibida de usar qualquer nome empresarial.','A indicação do tipo societário é irrelevante em todos os casos.','A limitada deve usar obrigatoriamente a expressão sociedade anônima.','A identificação do tipo societário no nome empresarial é requisito do regime da sociedade limitada.','Código Civil, art. 1.158'],
  ['emp-r10','empresarial','Personalidade jurídica','Sociedade regularmente constituída adquire personalidade jurídica e um credor pretende confundir automaticamente patrimônio social e patrimônio pessoal dos sócios sem hipótese legal de desconsideração.','A personalidade jurídica separa, em regra, os patrimônios da sociedade e dos sócios; eventual desconsideração exige os pressupostos legais aplicáveis.','A constituição da sociedade nunca produz separação patrimonial.','Todo credor social pode executar qualquer bem pessoal de qualquer sócio sem fundamento adicional.','Desconsideração da personalidade é automática em qualquer inadimplemento.','A autonomia patrimonial é elemento da pessoa jurídica, e sua superação é excepcional e condicionada ao regime legal.','Código Civil, arts. 49-A e 50']
];

const NAMES = ['Ana','Bruno','Carla','Diego','Elisa'];
const COMMANDS = [
  'À luz do direito brasileiro vigente, assinale a alternativa correta.',
  'Considerando a disciplina jurídica aplicável, qual solução está correta?',
  'A respeito da consequência jurídica do caso, assinale a opção correta.',
  'Segundo o regime legal aplicável à situação narrada, é correto afirmar que:',
  'Como deve ser resolvida juridicamente a situação?'
];

function rotateOptions(correct, wrongs, shift){
  const base=[correct,...wrongs];
  const target=shift%4;
  const options=new Array(4);options[target]=correct;
  let w=0;for(let i=0;i<4;i++)if(i!==target)options[i]=wrongs[(w++ + shift)%3];
  return {options,correct:target};
}

function surfaceFact(fact,variant){
  const name=NAMES[variant%NAMES.length];
  const leads=[
    `${name} procura orientação jurídica porque ${fact.charAt(0).toLowerCase()}${fact.slice(1)}`,
    `Em caso submetido à análise profissional, verifica-se que ${fact.charAt(0).toLowerCase()}${fact.slice(1)}`,
    `${name}, diante de situação concreta, relata o seguinte: ${fact}`,
    `Considere a seguinte situação prática: ${fact}`,
    `Em prova de aplicação normativa, toma-se como premissa que ${fact.charAt(0).toLowerCase()}${fact.slice(1)}`
  ];
  return `${leads[variant]} ${COMMANDS[variant]}`;
}

export function getExpandedQuestions(){
  const out=[];
  for(const rule of RULES){
    const [ruleId,subject,topic,fact,correct,w1,w2,w3,why,basis]=rule;
    const source=SOURCES[subject];
    for(let variant=0;variant<5;variant++){
      const rotated=rotateOptions(correct,[w1,w2,w3],variant);
      out.push({
        id:`${ruleId}-v${variant+1}`,
        ruleId,
        subject,
        topic,
        text:surfaceFact(fact,variant),
        options:rotated.options,
        correct:rotated.correct,
        explanation:why,
        difficulty:variant<2?3:variant<4?4:5,
        origin:'editorial-grounded',
        sourceType:'autoral-fonte-oficial',
        quality:'editorial-v3',
        sources:[{title:source.title,url:source.url,kind:'fonte oficial'}],
        legalBasis:[{label:basis,url:source.url}],
        verified:true,
        verification:{verified:true,confidence:.98,note:'Regra jurídica autoral ancorada em fonte normativa oficial.'},
        engineVersion:3
      });
    }
  }
  return out;
}

export const EXPANDED_RULE_COUNT = RULES.length;
export const EXPANDED_QUESTION_COUNT = RULES.length*5;
