import { getAllQuestions } from './question-bank.js';
const STORAGE_KEY='oab-aprova-premium-v1',DAY=86400000,HOUR=3600000;
const $=id=>document.getElementById(id),$$=s=>[...document.querySelectorAll(s)],SUBJECTS=window.OAB_SUBJECTS||[],INTEL=window.OAB_INTELLIGENCE||null;
const params=new URLSearchParams(location.search);let QUESTIONS=[],current=null,currentAnswered=null,state=load(),started=Date.now();
const BASES={etica:'Lei 8.906/1994, Código de Ética e Provimento 205/2021 quando pertinente.',constitucional:'Constituição Federal e legislação constitucional específica.',civil:'Código Civil.','processo-civil':'Código de Processo Civil.',penal:'Código Penal e leis penais especiais.','processo-penal':'CPP, LEP e legislação processual penal especial.',tributario:'Constituição Federal e CTN.',administrativo:'CF, Lei 14.133/2021, Lei 8.429/1992, LINDB e legislação pertinente.',empresarial:'Código Civil, Lei 6.404/1976 e Lei 11.101/2005.',trabalho:'Constituição Federal e CLT.','processo-trabalho':'CLT e CPC quando subsidiário.',consumidor:'CDC.',eca:'ECA.',humanos:'CF e tratados de direitos humanos.',eleitoral:'CF, Código Eleitoral e legislação eleitoral.',financeiro:'CF, Lei 4.320/1964 e LRF.',previdenciario:'CF e legislação previdenciária.',ambiental:'CF e legislação ambiental.',internacional:'CF, LINDB e tratados.',filosofia:'Teoria/autor indicado no enunciado.'};
function baseState(){return {version:4,profile:{strategy:'core'},attempts:[],reviews:{},sessions:[],guided:{seen:{},answered:0,correct:0},updatedAt:Date.now()};}
function load(){try{const r=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null'),b=baseState();return r?{...b,...r,profile:{...b.profile,...(r.profile||{})},guided:{...b.guided,...(r.guided||{})}}:b;}catch{return baseState();}}
function save(){state.updatedAt=Date.now();localStorage.setItem(STORAGE_KEY,JSON.stringify(state));}
function canon(v){try{return INTEL?.canonicalSubject(v)||v;}catch{return v;}}
function subjectName(id){return SUBJECTS.find(s=>s.id===canon(id))?.name||id;}
function isOfficial(q){return !!(q?.official||q?.origin==='official-fgv'||q?.sourceType==='fgv-official');}
function topic(q){if(!q)return null;try{return INTEL?.resolveTopic(q.subject,`${q.topic||''} ${q.text||''} ${(q.options||[]).join(' ')}`)||INTEL?.resolveTopic(q.subject,q.topic)||null;}catch{return null;}}
function topicLabel(q){return topic(q)?.label||String(q?.topic||'Conteúdo geral').replace(/\s*•\s*prova oficial/ig,'');}
function useful(q){const e=String(q?.explanation||'').trim();return (!e||/Gabarito definitivo oficial|sem comentário editorial automático/i.test(e))?null:e;}
function attemptsQ(q){return state.attempts.filter(a=>a.qid===q.id);}
function attemptsTopic(q){const sid=canon(q.subject),tid=topic(q)?.id||topicLabel(q);return state.attempts.filter(a=>canon(a.subject)===sid&&((INTEL?.resolveTopic(sid,a.topic)?.id)||a.topic)===tid);}
function recurrence(q){return {qWrong:attemptsQ(q).filter(a=>!a.correct).length,tWrong:attemptsTopic(q).filter(a=>!a.correct).length};}
function escapeHtml(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function notice(msg){$('notice').textContent=msg;$('notice').classList.remove('hidden');setTimeout(()=>$('notice').classList.add('hidden'),4000);}
function populate(){const sel=$('subjectFilter');sel.innerHTML='<option value="all">Todas</option>'+SUBJECTS.map(s=>`<option value="${s.id}">${s.name}</option>`).join('');const s=params.get('subject');if(s&&[...sel.options].some(o=>o.value===s))sel.value=s;const p=params.get('priority');if(p&&[...$('priorityFilter').options].some(o=>o.value===p))$('priorityFilter').value=p;}
function eligible(){const origin=$('originFilter').value,subject=$('subjectFilter').value,priority=$('priorityFilter').value;let qs=QUESTIONS.filter(q=>origin==='all'||(origin==='official'?isOfficial(q):!isOfficial(q)));if(subject!=='all')qs=qs.filter(q=>canon(q.subject)===canon(subject));if(priority==='review'){const ids=new Set(Object.values(state.reviews).filter(r=>!r.mastered).map(r=>r.qid));qs=qs.filter(q=>ids.has(q.id));}const requested=params.get('qid');if(requested){const one=QUESTIONS.find(q=>q.id===requested);if(one)return [one];}return qs;}
function pick(){let qs=eligible();if(!qs.length){$('questionArea').innerHTML='<div class="muted">Nenhuma questão neste filtro.</div>';return;}const priority=$('priorityFilter').value,subject=$('subjectFilter').value;if(priority==='adaptive'&&INTEL)qs=INTEL.selectAdaptiveQuestions(qs.map(q=>({...q,topic:topicLabel(q)})),state,{limit:Math.min(30,qs.length),strategy:state.profile?.strategy||'core',subject});else if(priority==='review')qs.sort((a,b)=>(state.reviews[a.id]?.due||0)-(state.reviews[b.id]?.due||0));else if(priority==='unseen'){const unseen=qs.filter(q=>!state.guided?.seen?.[q.id]);qs=unseen.length?unseen:qs;}else qs.sort(()=>Math.random()-.5);if(current&&qs.length>1)qs=qs.filter(q=>q.id!==current.id);current=qs[0];currentAnswered=null;started=Date.now();renderQuestion();$('analysisArea').innerHTML='<div class="panel"><p class="muted">Responda antes de consultar a análise.</p></div>';}
function updateReview(q,correct){const old=state.reviews[q.id];if(!correct){const wrong=(old?.wrongCount||0)+1;state.reviews[q.id]={...(old||{}),qid:q.id,subject:canon(q.subject),topic:topicLabel(q),due:Date.now()+(wrong>=2?8*HOUR:DAY),interval:wrong>=2?.33:1,streak:0,mastered:false,lastSeen:Date.now(),lastResult:false,cause:old?.cause||null,wrongCount:wrong,lapses:(old?.lapses||0)+1};return;}if(old){const ints=[3,7,14,30,60],streak=(old.streak||0)+1,interval=ints[Math.min(streak-1,ints.length-1)];state.reviews[q.id]={...old,due:Date.now()+interval*DAY,interval,streak,mastered:streak>=4,lastSeen:Date.now(),lastResult:true};}}
function answer(i){if(!current||currentAnswered)return;const correct=i===current.correct,timeMs=Date.now()-started;currentAnswered={choice:i,correct,timeMs,cause:null};state.attempts.push({qid:current.id,subject:canon(current.subject),topic:topicLabel(current),correct,choice:i,timeMs,mode:'guided',ts:Date.now(),cause:null,origin:current.origin||null});state.guided=state.guided||{seen:{},answered:0,correct:0};state.guided.seen=state.guided.seen||{};state.guided.seen[current.id]=Date.now();state.guided.answered=(state.guided.answered||0)+1;if(correct)state.guided.correct=(state.guided.correct||0)+1;updateReview(current,correct);save();renderQuestion();renderAnalysis();}
function setCause(c){if(!currentAnswered||currentAnswered.correct)return;currentAnswered.cause=c;const last=[...state.attempts].reverse().find(a=>a.qid===current.id&&a.mode==='guided');if(last)last.cause=c;if(state.reviews[current.id])state.reviews[current.id].cause=c;save();renderQuestion();renderAnalysis();}
function sameConcept(){const sid=canon(current.subject),tid=topic(current)?.id||topicLabel(current);return QUESTIONS.filter(q=>q.id!==current.id&&canon(q.subject)===sid&&((topic(q)?.id)||topicLabel(q))===tid);}
function reinforce(){let qs=sameConcept().filter(q=>!state.guided?.seen?.[q.id]);if(!qs.length)qs=sameConcept();if(!qs.length){notice('Não há outra questão desse conceito no banco atual.');return;}if(INTEL)qs=INTEL.selectAdaptiveQuestions(qs.map(q=>({...q,topic:topicLabel(q)})),state,{limit:qs.length,strategy:state.profile?.strategy||'core',subject:canon(current.subject)});current=qs[0];currentAnswered=null;started=Date.now();renderQuestion();$('analysisArea').innerHTML='<div class="panel"><p class="muted">Nova aplicação do mesmo conceito. Responda sem consultar a regra.</p></div>';window.scrollTo({top:0,behavior:'smooth'});}
function renderQuestion(){const q=current;if(!q)return;const a=currentAnswered,r=recurrence(q);$('questionArea').innerHTML=`<div class="tags"><span class="tag">${escapeHtml(isOfficial(q)?'FGV oficial':'Autoral')}</span><span class="tag">${escapeHtml(subjectName(q.subject))}</span><span class="tag">${escapeHtml(topicLabel(q))}</span>${r.qWrong>=2?'<span class="tag" style="background:#fff0ee;color:#8f3030">erro reincidente</span>':''}</div><h2>${escapeHtml(q.text)}</h2><div class="options">${q.options.map((o,i)=>{let cls='';if(a){if(i===q.correct)cls='correct';else if(i===a.choice)cls='wrong';}return `<button class="option ${cls}" data-choice="${i}" ${a?'disabled':''}><span class="letter">${String.fromCharCode(65+i)}</span><span>${escapeHtml(o)}</span></button>`}).join('')}</div>${a&&!a.correct?`<div class="block bad" style="margin-top:12px"><h3>Classifique a falha</h3><div class="cause"><button class="btn secondary ${a.cause==='knowledge'?'active':''}" data-cause="knowledge">Não sabia a regra</button><button class="btn secondary ${a.cause==='confusion'?'active':''}" data-cause="confusion">Confundi conceitos</button><button class="btn secondary ${a.cause==='reading'?'active':''}" data-cause="reading">Leitura/atenção</button></div></div>`:''}`;$$('[data-choice]').forEach(b=>b.onclick=()=>answer(+b.dataset.choice));$$('[data-cause]').forEach(b=>b.onclick=()=>setCause(b.dataset.cause));}
function renderAnalysis(){const q=current,a=currentAnswered;if(!a)return;const rec=recurrence(q),exp=useful(q),marked=q.options[a.choice],right=q.options[q.correct],cause=a.cause;let flaw='Classifique a causa para o diagnóstico ficar completo.';if(cause==='knowledge')flaw='A regra não estava disponível na memória. Leia a regra-base uma vez, feche o texto e explique com tuas palavras.';if(cause==='confusion')flaw='Houve mistura entre institutos/requisitos. O reforço deve comparar o elemento que muda o efeito jurídico.';if(cause==='reading')flaw='O problema foi leitura/atenção. Na próxima aplicação, leia primeiro o comando e procure negativa, exceção, prazo, competência e legitimidade.';$('analysisArea').innerHTML=`<div class="block ${a.correct?'good':'bad'}"><h3>Resultado</h3><p><b>${a.correct?'Correto':'Errado'}.</b> Gabarito ${String.fromCharCode(65+q.correct)}.</p></div><div class="block"><h3>Conceito cobrado</h3><p>${escapeHtml(topicLabel(q))}</p></div>${!a.correct?`<div class="block"><h3>Onde teu raciocínio desviou</h3><p><b>Marcada:</b> ${escapeHtml(marked)}<br><b>Correta:</b> ${escapeHtml(right)}<br>${escapeHtml(flaw)}</p></div>`:''}<div class="block"><h3>Base jurídica</h3><p>${escapeHtml(BASES[canon(q.subject)]||'Legislação específica do instituto cobrado.')}</p></div><div class="block"><h3>Regra que precisa ficar</h3><p>${escapeHtml(exp||'Reconstrua a proposição correta em uma frase e identifique o elemento que a FGV alterou no distrator: sujeito, requisito, exceção, prazo, competência ou efeito.')}</p></div><div class="block"><h3>Reincidência</h3><p>${rec.qWrong} erro(s) nesta questão • ${rec.tWrong} erro(s) neste conceito.</p></div><div class="block"><h3>Fixação</h3><p>Sem olhar, responda: qual é a regra? qual é a exceção? qual detalhe tornava a tua alternativa errada?</p><div class="row" style="margin-top:10px"><button class="btn primary" id="reinforce">Outra do mesmo conceito</button><a class="btn secondary" href="materiais.html?subject=${encodeURIComponent(canon(q.subject))}&q=${encodeURIComponent(topicLabel(q))}">Videoaula</a><a class="btn secondary" href="caderno.html?subject=${encodeURIComponent(canon(q.subject))}">Caderno</a></div></div>`;const b=$('reinforce');if(b)b.onclick=reinforce;}
$('applyFilters').onclick=pick;$('nextTop').onclick=pick;$('originFilter').onchange=()=>{};
async function boot(){populate();try{const imported=await getAllQuestions(),map=new Map((window.OAB_QUESTIONS||[]).map(q=>[q.id,q]));imported.forEach(q=>map.set(q.id,q));QUESTIONS=[...map.values()];}catch{QUESTIONS=[...(window.OAB_QUESTIONS||[])];}pick();}
boot();