(() => {
  'use strict';
  const DATA=window.OAB_SECOND_PHASE, $=id=>document.getElementById(id), $$=s=>[...document.querySelectorAll(s)];
  const KEY='oab-aprova-second-phase-v1';
  let state=load(), areaId=state.area||'administrativo', currentCase=null, draftSeconds=5400, draftHandle=null;
  let auth=null, functions=null;
  function load(){try{return {...{area:'administrativo',identifications:[],drafts:[],discursives:[]},...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return {area:'administrativo',identifications:[],drafts:[],discursives:[]}}}
  function save(){state.area=areaId;localStorage.setItem(KEY,JSON.stringify(state))}
  const area=()=>DATA.areas.find(a=>a.id===areaId)||DATA.areas[0];
  const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  function sample(arr){return arr[Math.floor(Math.random()*arr.length)]}
  function renderAreas(){
    $('areaList').innerHTML=DATA.areas.map(a=>`<button class="area-btn ${a.id===areaId?'active':''}" data-area="${a.id}"><strong>${a.short}</strong><span>${a.pieces.length} peças catalogadas</span></button>`).join('');
    $$('[data-area]').forEach(b=>b.onclick=()=>{areaId=b.dataset.area;save();renderAll();newIdentifyCase()});
  }
  function renderMap(){const a=area();$('areaTitle').textContent=a.name;$('areaTarget').textContent=`${Math.max(30,a.pieces.length*3)} identificações + 12 peças completas`;$('pieceCount').textContent=`${a.pieces.length} peças`;$('pieceGrid').innerHTML=a.pieces.map(p=>`<div class="piece-chip">${esc(p)}</div>`).join('');$('yieldPieces').innerHTML=a.highYield.map(p=>`<span class="chip">${esc(p)}</span>`).join('');$('statutes').innerHTML=a.statutes.map(p=>`<span class="chip">${esc(p)}</span>`).join('');$('latestPiece').textContent=`46º EOU: ${a.latest.piece}. ${a.latest.note}`;}
  function caseForArea(){const seeds=DATA.seedCases.filter(c=>c.area===areaId);return sample(seeds)}
  function newIdentifyCase(){currentCase=caseForArea(); if(!currentCase)return; $('idCaseTitle').textContent=currentCase.title;$('idCaseFacts').textContent=currentCase.facts;$('idFeedback').classList.add('hidden');const a=area(),wrong=a.pieces.filter(p=>p!==currentCase.piece).sort(()=>Math.random()-.5).slice(0,5),opts=[currentCase.piece,...wrong].sort(()=>Math.random()-.5);$('pieceChoices').innerHTML=opts.map(p=>`<button data-piece-choice="${esc(p)}">${esc(p)}</button>`).join('');$$('[data-piece-choice]').forEach(b=>b.onclick=()=>answerPiece(b,b.dataset.pieceChoice));loadDraftCase(currentCase)}
  function answerPiece(btn,choice){const correct=choice===currentCase.piece;state.identifications.push({area:areaId,caseId:currentCase.id,choice,correct,ts:Date.now()});state.identifications=state.identifications.slice(-500);save();$$('[data-piece-choice]').forEach(b=>{b.disabled=true;if(b.dataset.pieceChoice===currentCase.piece)b.classList.add('ok')});if(!correct)btn.classList.add('bad');$('idFeedback').classList.remove('hidden');$('idFeedback').innerHTML=`<strong>${correct?'Correto':'Peça correta: '+esc(currentCase.piece)}</strong><br>Gatilhos: ${currentCase.cues.map(esc).join(' • ')}`;renderMetrics()}
  function loadDraftCase(c){currentCase=c;$('draftCaseTitle').textContent=c.title;$('draftCaseFacts').textContent=c.facts;$('rubricBox').classList.add('hidden');$('gradeResult').classList.add('hidden')}
  function renderRubric(c=currentCase){$('rubricBox').innerHTML=c.rubric.map(([item,pts])=>`<div class="rubric-row"><span>${esc(item)}</span><strong>${pts.toFixed(2)}</strong></div>`).join('')+`<div class="rubric-row"><strong>Total</strong><strong>${c.rubric.reduce((s,x)=>s+x[1],0).toFixed(2)}</strong></div>`;$('rubricBox').classList.remove('hidden')}
  function startTimer(){clearInterval(draftHandle);draftSeconds=5400;tick();draftHandle=setInterval(()=>{draftSeconds--;tick();if(draftSeconds<=0)clearInterval(draftHandle)},1000)}
  function tick(){const m=Math.floor(draftSeconds/60),s=draftSeconds%60;$('draftTimer').textContent=`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`}
  async function ensureAuth(){if(auth?.currentUser)return true;alert('Entre com Google no Tutor IA para usar geração/correção por IA. O treino local continua funcionando.');return false}
  async function generateCase(){if(!(await ensureAuth()))return;const b=$('loadGeneratedCase');b.disabled=true;b.textContent='Gerando…';try{const call=functions.httpsCallable('generateSecondPhaseCase');const r=await call({area:areaId,kind:'piece'});if(r.data?.case){currentCase=r.data.case;loadDraftCase(currentCase)}}catch(e){alert('Não foi possível gerar o caso agora.')}finally{b.disabled=false;b.textContent='Gerar caso autoral com IA'}}
  async function gradeDraft(){const text=$('draftText').value.trim();if(text.length<300){alert('Redija uma peça mais completa antes da correção.');return}if(!(await ensureAuth())){renderRubric();return}const b=$('gradeDraft');b.disabled=true;b.textContent='Corrigindo…';try{const call=functions.httpsCallable('gradeSecondPhase');const r=await call({area:areaId,caseData:currentCase,answer:text});const g=r.data||{};state.drafts.push({area:areaId,caseId:currentCase.id||'ai',score:Number(g.score||0),piece:g.pieceIdentification||'',ts:Date.now()});state.drafts=state.drafts.slice(-200);save();$('gradeResult').classList.remove('hidden');$('gradeResult').innerHTML=`<strong>Nota estimada: ${Number(g.score||0).toFixed(2)}/5,00</strong><br>${esc(g.summary||'')}<br><br><strong>Prioridade:</strong> ${esc(g.priorityFix||'')}`;if(Array.isArray(g.items))$('gradeResult').innerHTML+=`<div class="rubric">${g.items.map(i=>`<div class="rubric-row"><span>${esc(i.item)}<br><small>${esc(i.feedback||'')}</small></span><strong>${Number(i.score||0).toFixed(2)}/${Number(i.max||0).toFixed(2)}</strong></div>`).join('')}</div>`;renderMetrics()}catch(e){alert('Falha na correção. Seu texto permanece salvo no navegador.')}finally{b.disabled=false;b.textContent='Corrigir por espelho'}}
  function localDiscursives(){const a=area();const prompts={administrativo:['Diferencie anulação e revogação de ato administrativo e indique o efeito temporal típico.','Explique os requisitos da responsabilidade civil objetiva do Estado.','Indique a sequência ordinária de fases da licitação na Lei 14.133/2021.','Explique quando cabe mandado de segurança contra ato administrativo.'],civil:['Diferencie prescrição e decadência quanto ao objeto atingido.','Explique os requisitos da tutela de urgência no CPC.','Indique quando cabem embargos de terceiro.','Explique a responsabilidade civil subjetiva e seus elementos.'],constitucional:['Explique a subsidiariedade na ADPF.','Diferencie ADI e ADC quanto ao objeto e finalidade.','Indique hipóteses de cabimento do mandado de injunção.','Explique o controle difuso de constitucionalidade.'],trabalho:['Indique os elementos da relação de emprego.','Explique os efeitos da revelia na Justiça do Trabalho.','Diferencie recurso ordinário e agravo de petição.','Explique a distribuição do ônus da prova na CLT.'],empresarial:['Explique a responsabilidade dos sócios na limitada.','Indique requisitos gerais da recuperação judicial.','Diferencie falência e recuperação judicial quanto à finalidade.','Explique a dissolução parcial de sociedade.'],penal:['Indique as hipóteses de absolvição sumária no procedimento comum.','Explique a ilicitude da prova e seus efeitos no CPP.','Diferencie apelação e recurso em sentido estrito.','Explique os requisitos da prisão preventiva.'],tributario:['Diferencie suspensão e extinção do crédito tributário.','Explique a exceção de pré-executividade na execução fiscal.','Indique os requisitos do mandado de segurança tributário.','Explique a vedação às sanções políticas como meio de cobrança de tributo.']};return (prompts[a.id]||[]).map((q,i)=>({id:`local-${a.id}-${i}`,question:q}))}
  async function generateDiscursives(){let items=localDiscursives();if(auth?.currentUser){try{const call=functions.httpsCallable('generateSecondPhaseCase');const r=await call({area:areaId,kind:'discursives'});if(Array.isArray(r.data?.discursives))items=r.data.discursives}catch{}}$('discursiveGrid').innerHTML=items.map((x,i)=>`<div class="disc-card"><strong>Questão ${i+1}</strong><p>${esc(x.question||x)}</p><textarea rows="6" style="width:100%;box-sizing:border-box" placeholder="Responda com conclusão + fundamento + dispositivo"></textarea></div>`).join('')}
  function renderMetrics(){const ids=state.identifications.filter(x=>x.area===areaId),drafts=state.drafts.filter(x=>x.area===areaId);$('mId').textContent=ids.length;$('mIdAcc').textContent=ids.length?`${Math.round(ids.filter(x=>x.correct).length/ids.length*100)}%`:'—';$('mDraft').textContent=drafts.length;$('mDraftAvg').textContent=drafts.length?`${(drafts.reduce((s,x)=>s+x.score,0)/drafts.length).toFixed(2)}/5`:'—';$('phaseHistory').innerHTML=[...drafts].reverse().slice(0,8).map(x=>`<div class="review-item"><div><strong>Peça corrigida • ${esc(x.piece||area().short)}</strong><small>${new Date(x.ts).toLocaleDateString('pt-BR')}</small></div><span class="due-tag">${x.score.toFixed(2)}/5</span></div>`).join('')||'<p class="muted">Ainda não há peças corrigidas nesta área.</p>'}
  function renderAll(){renderAreas();renderMap();renderMetrics();generateDiscursives();if(!currentCase||currentCase.area!==areaId)newIdentifyCase()}
  function bind(){$$('[data-tab]').forEach(b=>b.onclick=()=>{$$('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));$$('[data-panel]').forEach(p=>p.classList.toggle('active',p.dataset.panel===b.dataset.tab))});$('newIdCase').onclick=newIdentifyCase;$('showRubric').onclick=()=>renderRubric();$('startDraft').onclick=startTimer;$('loadGeneratedCase').onclick=generateCase;$('gradeDraft').onclick=gradeDraft;$('generateDisc').onclick=generateDiscursives}
  function initFirebase(){try{if(!window.firebase||!window.OAB_FIREBASE_CONFIG)return;if(!firebase.apps.length)firebase.initializeApp(window.OAB_FIREBASE_CONFIG);auth=firebase.auth();functions=firebase.app().functions('southamerica-east1')}catch(e){console.warn(e)}}
  bind();initFirebase();renderAll();tick();
})();
