import { initializeApp, getApps } from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-app.js';
import { getAuth, onAuthStateChanged } from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-auth.js';
import { getFirestore, doc, getDoc } from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-firestore.js';

const I=window.OAB_INTELLIGENCE,C=window.OAB_LEARNING_MATERIALS;
const KEY='oab-aprova-premium-v1',VIDEO_KEY='oab-aprova-private-video-catalog-v1';
const $=id=>document.getElementById(id);
let state=loadState(),selected=null;

function loadState(){try{return {attempts:[],reviews:{},profile:{strategy:'core',dailyMinutes:60},...JSON.parse(localStorage.getItem(KEY)||'{}')};}catch{return {attempts:[],reviews:{},profile:{strategy:'core',dailyMinutes:60}};}}
function pct(n){return `${Math.round((n||0)*100)}%`;}
function one(n){return Number(n||0).toFixed(1);}
function strategy(){return state.profile?.strategy==='balanced'?'balanced':'core';}
function videos(){try{const v=JSON.parse(localStorage.getItem(VIDEO_KEY)||'[]');return Array.isArray(v)?v:[];}catch{return [];}}
function countVideos(item){if(!item)return 0;return videos().filter(v=>{if(I.canonicalSubject(v.subject)!==item.subject)return false;try{return I.resolveTopic(v.subject,v.title)?.id===item.topic.id;}catch{return false;}}).length;}
function linkFor(item,type){if(!item)return '#';const s=encodeURIComponent(item.subject),t=encodeURIComponent(item.topic.id),label=encodeURIComponent(item.topic.label);if(type==='train')return `questao-guiada.html?subject=${s}&topic=${t}&priority=adaptive&origin=official`;if(type==='video')return `materiais.html?subject=${s}&q=${label}`;if(type==='notes')return `caderno.html?subject=${s}`;return '#';}

function renderExam(){$('examStatus').textContent=`48º EOU: edital previsto para ${new Date(I.EXAM.editalExpected+'T12:00:00').toLocaleDateString('pt-BR')}.`;$('examBasis').textContent=`${I.EXAM.distributionBasis} O motor deve ser recalibrado quando o edital oficial for publicado.`;}
function renderMetrics(){const r=I.readiness(state);$('mProjected').textContent=one(r.projected);$('mCoverage').textContent=pct(r.coverage);$('mRobust').textContent=pct(r.robust);$('mFragile').textContent=one(r.fragilePoints);$('mDue').textContent=String(r.due);}
function renderFocus(){const recs=I.recommendations(state,{strategy:strategy(),limit:5}),x=recs[0];if(!x)return;$('heroSubject').textContent=x.subjectName;$('heroTopic').textContent=x.topic.label;$('heroAction').textContent=`${x.action.label} • ~${x.action.minutes} min`;$('focusSubject').textContent=x.subjectName;$('focusTopic').textContent=x.topic.label;$('focusIndex').textContent=x.priorityIndex;$('actionBadge').textContent=x.action.label;$('focusWhy').textContent=I.explainRecommendation(x);$('focusExamValue').textContent=`${one(x.examValue)} q/prova*`;$('focusMastery').textContent=pct(x.stats.estimated);$('focusRecoverable').textContent=`+${one(x.recoverable)} pt*`;$('focusVideos').textContent=String(countVideos(x));$('prescriptionTitle').textContent=x.action.label;$('prescriptionText').textContent=x.action.description;$('heroTrain').href=linkFor(x,'train');$('heroVideo').href=linkFor(x,'video');$('heroNotebook').href=linkFor(x,'notes');$('focusTrain').href=linkFor(x,'train');$('focusVideo').href=linkFor(x,'video');$('focusNotes').href=linkFor(x,'notes');$('queue').innerHTML=recs.map((r,i)=>`<div class="queue-item"><b>${i+1}</b><div><strong>${r.subjectName} • ${r.topic.label}</strong><span>${r.action.label} • domínio ${pct(r.stats.estimated)} • +${one(r.recoverable)} pt recuperável*</span></div><div class="queue-actions"><a class="mini-link" href="${linkFor(r,'train')}">treinar</a><a class="mini-link" href="${linkFor(r,'video')}">aula</a></div></div>`).join('');renderToday(recs);}
function renderToday(recs){const mins=Math.max(20,Number(state.profile?.dailyMinutes||60)),due=Object.values(state.reviews||{}).filter(r=>!r.mastered&&Number(r.due||0)<=Date.now()).length,review=Math.min(due?20:8,Math.max(6,Math.round(mins*.22))),left=Math.max(12,mins-review),a=Math.round(left*.58),b=left-a,r1=recs[0],r2=recs[1]||r1;$('todayTitle').textContent=`Plano de ${mins} min`;$('todayPlan').innerHTML=`<div class="today-step"><b>${review} min</b><div><strong>${due?`Revisar ${Math.min(due,6)} vencida(s)`:'Recuperação ativa curta'}</strong><span>${due?'Proteja pontos já conquistados antes de abrir matéria nova.':'Comece tentando lembrar regras sem consulta.'}</span></div></div><div class="today-step"><b>${a} min</b><div><strong>${r1?.subjectName||'Ética'} • ${r1?.topic.label||'diagnóstico'}</strong><span>${r1?.action.label||'Questões'}; termine com nova aplicação sem consulta.</span></div></div><div class="today-step"><b>${b} min</b><div><strong>${r2?.subjectName||'Constitucional'} • ${r2?.topic.label||'diagnóstico'}</strong><span>Intercale outro tema de alto valor para reduzir falsa fluência.</span></div></div>`;}
function renderSubjects(){const ids=Object.keys(I.SUBJECTS).filter(id=>I.SUBJECTS[id].core);if(!selected)selected=I.recommendations(state,{strategy:'core',limit:1})[0]?.subject||ids[0];$('subjectCloud').innerHTML=ids.map(id=>`<button class="subject-chip ${selected===id?'active':''}" data-s="${id}">${I.SUBJECTS[id].name}</button>`).join('');document.querySelectorAll('[data-s]').forEach(b=>b.onclick=()=>{selected=b.dataset.s;renderSubjects();renderTopicTable();});}
function renderTopicTable(){const rows=I.rankTopics(state,{subject:selected});$('topicTable').innerHTML=rows.map(x=>`<div class="topic-row"><div><strong>${x.topic.label}</strong><span>${x.topic.historicalCount} questões em 16 exames • ${Math.round(x.topic.historicalShare*100)}% da matéria</span></div><b>${pct(x.stats.estimated)}</b><em>${countVideos(x)} aula(s)</em></div>`).join('');}
function renderMethod(){const steps=C?.cycle||[];$('methodGrid').innerHTML=steps.map((s,i)=>`<div><b>${i+1}</b><strong>${s.label}</strong><span>${s.description}</span></div>`).join('');}
function renderAll(){renderExam();renderMetrics();renderFocus();renderSubjects();renderTopicTable();renderMethod();}

renderAll();
try{const app=getApps()[0]||initializeApp(window.OAB_FIREBASE_CONFIG),auth=getAuth(app),db=getFirestore(app);onAuthStateChanged(auth,async user=>{if(!user)return;try{const snap=await getDoc(doc(db,'users',user.uid,'state','main'));if(snap.exists()&&Number(snap.data()?.updatedAt||0)>Number(state.updatedAt||0)){state={...state,...snap.data(),profile:{...state.profile,...(snap.data().profile||{})}};localStorage.setItem(KEY,JSON.stringify(state));renderAll();}}catch{}});}catch{}
